In [1]:
import pandas as pd
from anndata import read_h5ad

adata = read_h5ad('/Users/kylekimler/Projects/GCA/meta_datasets/tracker_upload_next/hgca_all_lineages_v1.h5ad')

def normalize_tissue(x):
    if pd.isna(x):
        return x
    x = str(x).strip().lower()
    fixes = {
        "ascending_colon": "ascending colon",
        "transverse_colon": "transverse colon",
        "descending_colon": "descending colon",
        "sigmoid_colon": "sigmoid colon",
        "small_intestine": "small intestine",
        "vermiform_appendix": "vermiform appendix",
        "gastrointestinal_system_mesentery": "gastrointestinal system mesentery"
    }
    x = fixes.get(x, x)
    return x

adata.obs["tissue_clean"] = adata.obs["tissue_ontology_term"].map(normalize_tissue)

counts = (
    adata.obs["tissue_clean"]
    .value_counts(dropna=False)
    .rename_axis("tissue")
    .reset_index(name="n_cells")
)

counts

                               tissue  n_cells
0                               ileum   413476
1                             jejunum   193320
2                               colon   139192
3                     ascending colon   106469
4   gastrointestinal system mesentery    26430
5                       sigmoid colon    17062
6                    transverse colon    16978
7                            duodenum    12815
8                              caecum    12650
9                              rectum    12502
10                    small intestine     2739
11                   descending colon     2706
12                 vermiform appendix      984

In [2]:
segment_order = [
    "duodenum",
    "jejunum",
    "ileum",
    "caecum",
    "ascending colon",
    "transverse colon",
    "descending colon",
    "sigmoid colon",
    "rectum",
    "vermiform appendix",
    "gastrointestinal system mesentery"
]

plot_df = counts[counts["tissue"].isin(segment_order)].copy()
plot_df["tissue"] = pd.Categorical(plot_df["tissue"], categories=segment_order, ordered=True)
plot_df = plot_df.sort_values("tissue")
plot_df

                               tissue  n_cells
7                            duodenum    12815
1                             jejunum   193320
0                               ileum   413476
8                              caecum    12650
3                     ascending colon   106469
6                    transverse colon    16978
11                   descending colon     2706
5                       sigmoid colon    17062
9                              rectum    12502
12                 vermiform appendix      984
4   gastrointestinal system mesentery    26430