# LIANA (ileum) — epithelial–glia & FARM–T interactions

Ileum LIANA results (`ileum_corrected_liana.csv`) are large (~40M rows). The notebook reads the CSV **once** in chunks, keeps only rows touching predefined `source`/`target` labels, then subsets for neurotransmitter / axon-related ligand–receptor names.

Atlas cell types in `AnnData` use `obs['hgca_celltype_v1']` (loaded in **backed** mode for metadata only).

### Figures
Exports follow the [Nature research figure guide](https://research-figure-guide.nature.com/figures/): **Helvetica**, **black** labels, colour-blind–friendly palette from *Building and exporting figure panels*, **vector PDF** (`pdf.fonttype=42`). Further Illustrator edits → save as **.ai**; otherwise use the **.pdf** from this notebook.
### Neuropod / NCAM / GDNF–RET module
§**2.2** adds **Glia ↔ EEC I (CCK+)** to the epithelial–glia watchlist, then filters ileum LIANA for **NCAM/IgCAM**, **GDNF-family ligands and RET/GFRα co-receptors**, and **neurofilament** L–R tokens, plus optional **NEFL/NEFM/NEFH/NCAM1/GDNF/RET/GFRA1** expression summaries. **Re-run** the chunked LIANA load cell after pulling this update so `EEC I Cells (CCK+)` rows enter `dfw`.

In [1]:
from __future__ import annotations

import re
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import scanpy as sc
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.patches import Patch

# --- paths (edit if your GCA tree differs) ---
GCA_ROOT = Path.home() / "Projects" / "GCA"
INTEGRATED = GCA_ROOT / "meta_datasets" / "integrated-objects" / "hgca_all_lineages_v1.h5ad"
LIANA_ILEUM = GCA_ROOT / "downstream_data" / "ileum_corrected_liana.csv"
FIG_DIR = GCA_ROOT / "github_vignette_output" / "LIANA" / "ileum_figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

print("INTEGRATED:", INTEGRATED, "exists:", INTEGRATED.is_file())
print("LIANA_ILEUM:", LIANA_ILEUM, "exists:", LIANA_ILEUM.is_file())
print("FIG_DIR:", FIG_DIR)

INTEGRATED: /Users/kylekimler/Projects/GCA/meta_datasets/integrated-objects/hgca_all_lineages_v1.h5ad exists: True
LIANA_ILEUM: /Users/kylekimler/Projects/GCA/downstream_data/ileum_corrected_liana.csv exists: True
FIG_DIR: /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures

/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/louvain/__init__.py:54: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import get_distribution, DistributionNotFound

In [2]:
# Nature — "Building and exporting figure panels" palette (colour-blind friendly)
# https://research-figure-guide.nature.com/figures/building-and-exporting-figure-panels/
NATURE_WONG = {
    "black": "#000000",
    "orange": "#e69f00",
    "sky_blue": "#56b4e9",
    "bluish_green": "#009e73",
    "yellow": "#f0e442",
    "blue": "#0072b2",
    "vermillion": "#d55e00",
    "reddish_purple": "#cc79a7",
}
NATURE_CYCLE = [
    NATURE_WONG["orange"],
    NATURE_WONG["sky_blue"],
    NATURE_WONG["bluish_green"],
    NATURE_WONG["blue"],
    NATURE_WONG["vermillion"],
    NATURE_WONG["reddish_purple"],
    NATURE_WONG["yellow"],
]


def setup_nature_style() -> None:
    plt.rcParams.update(
        {
            "font.family": "sans-serif",
            "font.sans-serif": ["Helvetica", "Helvetica Neue", "Arial", "DejaVu Sans"],
            "font.size": 7,
            "axes.labelsize": 7,
            "axes.titlesize": 7,
            "figure.titlesize": 7,
            "xtick.labelsize": 6,
            "ytick.labelsize": 6,
            "legend.fontsize": 6,
            "axes.linewidth": 0.6,
            "xtick.major.width": 0.6,
            "ytick.major.width": 0.6,
            "lines.linewidth": 0.9,
            "axes.grid": False,
            "text.color": NATURE_WONG["black"],
            "axes.labelcolor": NATURE_WONG["black"],
            "axes.edgecolor": NATURE_WONG["black"],
            "xtick.color": NATURE_WONG["black"],
            "ytick.color": NATURE_WONG["black"],
            "axes.titlecolor": NATURE_WONG["black"],
            "pdf.fonttype": 42,
            "ps.fonttype": 42,
            "savefig.transparent": False,
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "savefig.facecolor": "white",
        }
    )


def save_pdf(fig: mpl.figure.Figure, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(
        path,
        format="pdf",
        bbox_inches="tight",
        pad_inches=0.08,
        metadata={"Creator": "LIANA_analysis.ipynb"},
    )
    plt.close(fig)
    print("Saved", path)


def shorten_label(s: str, max_len: int = 46) -> str:
    s = str(s)
    return s if len(s) <= max_len else s[: max_len - 1] + "…"


def add_lr_pair_column(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()
    out["lr_pair"] = (
        out["ligand_complex"].astype(str) + " — " + out["receptor_complex"].astype(str)
    ).map(shorten_label)
    return out


def max_lr_per_pair(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return pd.DataFrame(columns=["ligand_complex", "receptor_complex", "lrscore"])
    return (
        df.groupby(["ligand_complex", "receptor_complex"], as_index=False)["lrscore"]
        .max()
        .sort_values("lrscore", ascending=False)
    )


def panel_label(ax: mpl.axes.Axes, tag: str) -> None:
    ax.text(
        0.0,
        1.02,
        tag,
        transform=ax.transAxes,
        fontsize=8,
        fontweight="bold",
        color=NATURE_WONG["black"],
        va="bottom",
        ha="left",
    )


def hbar_top_lr(df: pd.DataFrame, ax: mpl.axes.Axes, title: str, n: int = 10) -> None:
    d = add_lr_pair_column(df.head(n))
    if d.empty:
        ax.set_axis_off()
        ax.text(0.5, 0.5, "No interactions", ha="center", va="center", fontsize=7, color=NATURE_WONG["black"])
        return
    colors = [NATURE_CYCLE[i % len(NATURE_CYCLE)] for i in range(len(d))]
    y = np.arange(len(d))
    ax.barh(y, d["lrscore"], color=colors, edgecolor=NATURE_WONG["black"], linewidth=0.35)
    ax.set_yticks(y)
    ax.set_yticklabels(d["lr_pair"], fontsize=5.5, color=NATURE_WONG["black"])
    ax.invert_yaxis()
    ax.set_xlabel("LIANA lrscore (unitless)", color=NATURE_WONG["black"])
    ax.set_title(title, fontsize=7, color=NATURE_WONG["black"])
    ax.tick_params(axis="both", colors=NATURE_WONG["black"])
    ax.tick_params(axis="x", which="major", length=3)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)


NATURE_CMAP = LinearSegmentedColormap.from_list(
    "nat_seq", ["#ffffff", NATURE_WONG["sky_blue"], NATURE_WONG["blue"], NATURE_WONG["black"]]
)

# LIANA direction (same convention for all figures: ligand on source, receptor on target)
LIANA_NOTE_GLIA_HEATMAP = (
    "Direction: ligand on source cells, receptor on target cells (LIANA source/target). "
    "Row label = ligand and receptor (not an arrow). "
    "Each cell = max lrscore over Glia-to-epithelium and epithelium-to-Glia for that L-R pair."
)
LIANA_NOTE_GLIA_BARS = (
    "Direction: ligand on source, receptor on target; each bar = max lrscore over both directions "
    "(Glia-to-epithelium and epithelium-to-Glia)."
)
LIANA_NOTE_FARM_BARS = (
    "Direction: ligand on source, receptor on target; each bar = max lrscore over both directions "
    "(FARM-to-CD4 and CD4-to-FARM)."
)
LIANA_NOTE_FARM_HEATMAP = (
    "Direction: ligand on source, receptor on target; each cell = max lrscore over FARM-to-CD4 and CD4-to-FARM."
)
LIANA_NOTE_SHORT = (
    "Direction: ligand on source, receptor on target; each plotted value = max lrscore over both directions (A-to-B and B-to-A)."
)

setup_nature_style()

## 1. Atlas metadata (`hgca_celltype_v1`)
Backed read: **no** expression matrix in memory.

In [3]:
adata = sc.read_h5ad(INTEGRATED, backed="r")
assert "hgca_celltype_v1" in adata.obs.columns, adata.obs.columns[:20]

ct = adata.obs["hgca_celltype_v1"].astype("string")
print(adata.n_obs, "cells")
display(ct.value_counts().head(25))

for label in [
    "Glia",
    "EEC L",
    "EEC Progenitors",
    "BEST4 Enterocytes",
    "Tuft Cells",
    "Follicle Associated Resident Macrophages",
    "CD4 Tr1",
    "CD4 Tfr",
    "Gamma Delta T Cells",
    "NKT Cells",
]:
    n = int((ct == label).sum())
    print(f"{label!r}: {n}")

if hasattr(adata, "file") and adata.file is not None:
    adata.file.close()

944502 cells

hgca_celltype_v1
CD8 TRM                              130081
Villus Tip Enterocytes                62858
CD4 Memory                            55896
Memory B                              45602
CD4 Th17                              45218
CD8 IEL                               41143
Plasma Cells                          38083
Naive B                               33898
Plasma IGA                            31875
Mid Villus Enterocytes                30619
CD4 Tfh                               24832
Lower Crypt Colonocytes               21199
Goblet Cells                          20309
CD8 Circulating Effector Memory       18471
Transiently Amplifying Cells (TA)     18299
Lower Villus Enterocytes              18149
Crypt Top Colonocytes                 18075
Mast Cells                            17702
Mature Goblet Cells                   17419
NKT Cells                             17114
CD4 Naive                             16416
Lamina propria Fibroblasts (S1)       16327
Colonocyte Progenitors                13609
Enterocyte Progenitors                12589
M0 Macrophages                        12307
Name: count, dtype: Int64

'Glia': 2604
'EEC L': 473
'EEC Progenitors': 546
'BEST4 Enterocytes': 2691
'Tuft Cells': 2993
'Follicle Associated Resident Macrophages': 902
'CD4 Tr1': 1878
'CD4 Tfr': 2407
'Gamma Delta T Cells': 2946
'NKT Cells': 17114

## 2. Load ileum LIANA efficiently (one chunked pass)

LIANA column names follow the export: `source`, `target`, `ligand_complex`, `receptor_complex`, `lrscore`, …

We first restrict to rows where **either** `source` or `target` is in a small whitelist of cell-type strings used below, then assign each row to interaction groups.

In [4]:
# LIANA label sets (must match strings in the CSV)
GLIA = {"Glia"}

EEC_L = {"EEC L"}
# I cells (CCK+); label must match hgca_celltype_v1 in the LIANA CSV
EEC_I = {"EEC I Cells (CCK+)", "EEC I"}  # second alias if present in hgca_celltype_v1
# Mature EEC (exclude progenitors; those are analysed separately)
EEC_MAT = {
    "EEC N",
    "EEC S",
    "EEC L",
    "EEC I Cells (CCK+)",
    "EEC I",
    "Enteroendocrine Cells (EEC)",
    "EEC Enterochromaffin (EC)",
}
BEST4_ILEUM = {"BEST4 Enterocytes"}  # ileum BEST4 enterocytes
BEST4_COLON = {"BEST4 Colonocytes"}
BEST4_BOTH = {"BEST4 Enterocytes", "BEST4 Colonocytes"}
VILLUS_BOTTOM = {"Lower Villus Enterocytes"}  # control epithelium (non-neuropod-focused)
TUFT = {"Tuft Cells"}
TUFT_PROG = {"Tuft Progenitors"}
EEC_PROG = {"EEC Progenitors"}
SEC_PROG = {"Secretory Progenitors"}

FARM = {"Follicle Associated Resident Macrophages"}
T_WITH_FARM = {
    "CD4 Tr1",
    "CD4 Tfr",
    "CD4 Tfh",
    "CD4 pTreg",
    "CD4 Th17",
    "CD4 tTreg",
    "NKT Cells",
    "Gamma Delta T Cells",
}

ALL_WATCH = (
    GLIA
    | EEC_MAT
    | BEST4_BOTH
    | VILLUS_BOTTOM
    | TUFT
    | TUFT_PROG
    | EEC_PROG
    | SEC_PROG
    | FARM
    | T_WITH_FARM
)


def bidirectional_mask(df: pd.DataFrame, a: set[str], b: set[str]) -> pd.Series:
    return (
        (df["source"].isin(a) & df["target"].isin(b))
        | (df["source"].isin(b) & df["target"].isin(a))
    )


def neuro_axon_mask(df: pd.DataFrame) -> pd.Series:
    """Heuristic keyword filter on ligand/receptor complex symbols."""
    lr = (
        df["ligand_complex"].astype(str)
        + "|"
        + df["receptor_complex"].astype(str)
    ).str.upper()
    neuro = [
        "GABA",
        "GABR",
        "GRIA",
        "GRIN",
        "GRM",
        "GAD",
        "SLC6A",
        "SLC17A",
        "SLC32A",
        "HTR",
        "DRD",
        "CHRM",
        "CHRNA",
        "CHRNB",
        "TPH",
        "DDC",
        "DBH",
        "COMT",
        "MAOA",
        "ACHE",
        "CHAT",
        "SLC18A",
        "ADRA",
        "ADRB",
        "DOP",
        "5-HT",
        "SEROT",
        "GLUT",
        "NOS1",
        "NTS",
        "TACR",
        "GRP",
        "CCK",
        "PYY",
        "NPY",
        "POMC",
    ]
    axon = [
        "NGF",
        "NTRK",
        "TRK",
        "BDNF",
        "GDNF",
        "ROBO",
        "SLIT",
        "SEMA",
        "PLXA",
        "NRP",
        "UNC5",
        "DCC",
        "RTN",
        "L1CAM",
        "NCAM",
        "NRXN",
        "NLGN",
        "CNTN",
        "LINGO",
        "EPHA",
        "EPHB",
        "EFNA",
        "EFNB",
        "WNT",
        "NTN",
        "PTPR",
        "PTN",
    ]
    keys = sorted(set(neuro + axon))
    pat = "|".join(re.escape(k) for k in keys)
    return lr.str.contains(pat, regex=True, na=False)


def _primary_ligand_token(s: str) -> str:
    """First symbol of LIANA ligand_complex (handles PYY^DPP4-style complexes)."""
    t = str(s).strip().upper()
    for sep in ("^", "+", "_", "|"):
        if sep in t:
            t = t.split(sep, 1)[0]
            break
    return t.strip()


def reduce_canonical_neuropeptide_outgoing(df: pd.DataFrame) -> pd.DataFrame:
    """Keep one canonical outgoing L–R per PYY, SST, NTS, TPH1 (best lrscore among canonical receptors). Drops non-canonical rows; if no canonical receptor, drops all rows for that hormone."""
    if df.empty:
        return df
    out = df.copy()
    lig_tok = out["ligand_complex"].map(_primary_ligand_token)
    rec_u = out["receptor_complex"].astype(str).str.upper()
    # Canonical receptor priority (gut / neuroendocrine literature)
    CANONICAL = {
        "PYY": ["NPY1R", "NPY2R"],
        "SST": ["SSTR2", "SSTR1", "SSTR5"],
        "NTS": ["NTSR1", "NTSR2", "NGFR", "SORT1"],
        "TPH1": ["HTR1A", "HTR2A", "HTR3A", "HTR1B"],
    }
    drop_idx: list = []
    for horm, recs in CANONICAL.items():
        m = lig_tok == horm.upper()
        if not m.any():
            continue
        idx_all = out.index[m]
        best_idx = None
        best_score = -np.inf
        for r in recs:
            mm = m & (rec_u == r.upper())
            if mm.any():
                bi = out.loc[mm, "lrscore"].idxmax()
                sc = float(out.loc[bi, "lrscore"])
                if sc > best_score:
                    best_score = sc
                    best_idx = bi
        if best_idx is None:
            drop_idx.extend(idx_all.tolist())
        else:
            drop_idx.extend([i for i in idx_all if i != best_idx])
    return out.drop(index=drop_idx, errors="ignore")


USECOLS = [
    "source",
    "target",
    "ligand_complex",
    "receptor_complex",
    "lr_means",
    "lrscore",
    "cellphone_pvals",
    "spec_weight",
]


def load_liana_watchlist(
    path: Path,
    watch: set[str],
    chunksize: int = 1_000_000,
) -> pd.DataFrame:
    parts: list[pd.DataFrame] = []
    for i, chunk in enumerate(pd.read_csv(path, usecols=USECOLS, chunksize=chunksize)):
        sub = chunk[chunk["source"].isin(watch) | chunk["target"].isin(watch)]
        if len(sub):
            parts.append(sub)
        if (i + 1) % 10 == 0:
            print(f"chunks processed: {i + 1}, rows kept so far: {sum(len(p) for p in parts):,}")
    if not parts:
        return pd.DataFrame(columns=USECOLS)
    return pd.concat(parts, ignore_index=True)


dfw = load_liana_watchlist(LIANA_ILEUM, ALL_WATCH)
print("Filtered rows (touching watchlist cell types):", len(dfw))
dfw.head()

chunks processed: 10, rows kept so far: 4,003,403
chunks processed: 20, rows kept so far: 8,208,782
chunks processed: 30, rows kept so far: 12,279,288
Filtered rows (touching watchlist cell types): 16196312

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
0,Mature Goblet Cells,Gamma Delta T Cells,TFF3,CXCR4,1580.0220,0.0,0.015594,0.993948
1,Neutrophils,CD4 Th17,S100A8,CD69,1532.0663,0.0,0.045527,0.993989
2,Mature Goblet Cells,CD4 Tfh,TFF3,CXCR4,1554.8007,0.0,0.011118,0.992840
3,Mature Goblet Cells,CD4 Tfr,TFF3,CXCR4,1544.6865,0.0,0.009324,0.992187
4,Mature Goblet Cells,CD4 Th17,TFF3,CXCR4,1542.5238,0.0,0.008940,0.992022

### 2.1 Epithelium / progenitors ↔ Glia
Bidirectional; sorted by `lrscore`.

In [5]:
groups = {
    "EEC L <-> Glia": bidirectional_mask(dfw, EEC_L, GLIA),
    "EEC I (CCK+) <-> Glia": bidirectional_mask(dfw, EEC_I, GLIA),
    "EEC (mature) <-> Glia": bidirectional_mask(dfw, EEC_MAT, GLIA),
    "BEST4 Enterocyte <-> Glia": bidirectional_mask(dfw, BEST4_ILEUM, GLIA),
    "BEST4 Colonocytes <-> Glia": bidirectional_mask(dfw, BEST4_COLON, GLIA),
    "Tuft <-> Glia": bidirectional_mask(dfw, TUFT, GLIA),
    "EEC Progenitors <-> Glia": bidirectional_mask(dfw, EEC_PROG, GLIA),
    "Tuft Progenitors <-> Glia": bidirectional_mask(dfw, TUFT_PROG, GLIA),
    "Secretory Progenitors <-> Glia": bidirectional_mask(dfw, SEC_PROG, GLIA),
    "Villus-bottom enterocytes <-> Glia": bidirectional_mask(dfw, VILLUS_BOTTOM, GLIA),
}

glia_tables = {}
for name, m in groups.items():
    sub = dfw.loc[m].copy()
    sub = sub.sort_values("lrscore", ascending=False)
    sub = reduce_canonical_neuropeptide_outgoing(sub)
    glia_tables[name] = sub
    print(f"\n=== {name} ===")
    print("n interactions:", len(sub))
    if len(sub):
        display(sub.head(15))
        na = sub[neuro_axon_mask(sub)]
        print("  neuro/axon keyword hits:", len(na))
        if len(na):
            display(na.head(20))

=== EEC L <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
2726,EEC L,Glia,NTS,NGFR,353.027830,0.000,0.084818,0.975630
9838,Glia,EEC L,LGALS1,ITGB1,175.177100,0.000,0.000536,0.953212
4324,Glia,EEC L,VIM,CD44,280.384980,0.000,0.000256,0.949593
54492,EEC L,Glia,MDK,PTPRZ1,69.008590,0.000,0.060507,0.937370
51797,EEC L,Glia,HLA-A,APLP2,70.918400,1.000,0.000168,0.934046
34982,Glia,EEC L,S100A4,ERBB3,88.815450,0.000,0.001447,0.930978
19581,Glia,EEC L,SPP1,CD44,122.733850,0.000,0.004539,0.924691
100154,EEC L,Glia,TTR,NGFR,49.391304,0.000,0.114665,0.917962
91663,Glia,EEC L,TIMP1,CD63,52.005157,0.000,0.000118,0.916572
33060,Glia,EEC L,HLA-A,APLP2,91.757950,0.001,0.000097,0.915079
33856,Glia,EEC L,TIMP3,CD44,90.473880,0.000,0.000469,0.912588
79321,Glia,EEC L,L1CAM,ERBB3,56.380653,0.000,0.040639,0.911346
83498,EEC L,Glia,MDK,NCL,54.976364,0.000,0.000545,0.907115
9389,EEC L,Glia,TFF3,ACKR3,180.092270,0.004,0.000957,0.906214
44600,Glia,EEC L,COL1A2,CD44,77.255020,0.000,0.000286,0.905529

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
2726,EEC L,Glia,NTS,NGFR,353.027830,0.000,0.084818,0.975630
54492,EEC L,Glia,MDK,PTPRZ1,69.008590,0.000,0.060507,0.937370
100154,EEC L,Glia,TTR,NGFR,49.391304,0.000,0.114665,0.917962
79321,Glia,EEC L,L1CAM,ERBB3,56.380653,0.000,0.040639,0.911346
149730,EEC L,Glia,RTN4,NGFR,38.121513,0.000,0.008577,0.893486
94049,Glia,EEC L,NCAM1,CACNA1C,51.224140,0.000,0.018512,0.892414
97740,EEC L,Glia,CALM1,PTPRA,50.344807,0.000,0.000270,0.888977
96169,Glia,EEC L,L1CAM,CD9,50.725388,0.000,0.004383,0.879625
176863,EEC L,Glia,APP,NGFR,34.357460,0.000,0.009033,0.878264
101761,Glia,EEC L,NCAM1,PTPRA,48.849040,0.000,0.004741,0.873333
147389,Glia,EEC L,CALM1,PTPRA,38.523136,0.815,0.000153,0.857588
102689,Glia,EEC L,L1CAM,EPHB2,48.552753,0.000,0.026080,0.852328
325566,Glia,EEC L,SLIT2,APP,23.056220,0.000,0.002034,0.839081
201323,EEC L,Glia,RARRES1,NRP2,31.710660,0.000,0.002347,0.827754
172651,Glia,EEC L,NLGN4X,NRXN1,34.961136,0.000,0.004270,0.785675
111064,Glia,EEC L,L1CAM,EGFR,46.274494,0.000,0.008008,0.777798
117000,Glia,EEC L,NCAM1,FGFR1,44.784798,0.000,0.002920,0.769493
111989,Glia,EEC L,L1CAM,ERBB2,46.013260,0.000,0.009116,0.758253
117929,Glia,EEC L,NCAM1,GFRA1,44.563442,0.000,0.008344,0.751668
75567,EEC L,Glia,GCG,ADRB2,233.236680,0.000,0.001098,0.744803

=== EEC (mature) <-> Glia ===
n interactions: 44564

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
19,EEC N,Glia,NTS,NGFR,1137.159300,0.000,0.286745,0.986597
360,EEC S,Glia,APOA1,LRP1,806.551400,0.000,0.007778,0.968354
364,EEC S,Glia,APOA1,ABCA1,806.548340,0.000,0.009017,0.968346
4263,Glia,Enteroendocrine Cells (EEC),VIM,CD44,281.929080,0.000,0.000318,0.954591
9838,Glia,EEC L,LGALS1,ITGB1,175.177100,0.000,0.000536,0.953212
36598,Glia,Enteroendocrine Cells (EEC),NCAM1,CACNA1C,86.432846,0.000,0.103334,0.951451
4324,Glia,EEC L,VIM,CD44,280.384980,0.000,0.000256,0.949593
3532,EEC S,Glia,APOA4,LRP1,305.594120,0.000,0.006655,0.949304
25520,EEC S,Glia,HLA-A,APLP2,108.321370,0.000,0.000289,0.948850
10097,Glia,EEC N,LGALS1,ITGB1,172.263900,0.000,0.000410,0.946864
10100,Glia,EEC Enterochromaffin (EC),LGALS1,ITGB1,172.211500,0.000,0.000408,0.946724
4352,Glia,EEC Enterochromaffin (EC),VIM,CD44,279.453060,0.000,0.000218,0.945618
45279,Glia,EEC S,APP,CD74,76.637985,0.911,0.000168,0.945372
45877,Glia,Enteroendocrine Cells (EEC),CALM1,CACNA1C,76.106930,0.000,0.003324,0.944803
41523,EEC N,Glia,TTR,NGFR,79.864914,0.000,0.250469,0.942980

  neuro/axon keyword hits: 10613

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
19,EEC N,Glia,NTS,NGFR,1137.159300,0.0,0.286745,0.986597
36598,Glia,Enteroendocrine Cells (EEC),NCAM1,CACNA1C,86.432846,0.0,0.103334,0.951451
41523,EEC N,Glia,TTR,NGFR,79.864914,0.0,0.250469,0.942980
54492,EEC L,Glia,MDK,PTPRZ1,69.008590,0.0,0.060507,0.937370
55505,Glia,EEC Enterochromaffin (EC),NCAM1,CACNA1C,68.392940,0.0,0.059874,0.937177
74872,EEC Enterochromaffin (EC),Glia,TTR,NGFR,58.122414,0.0,0.153574,0.928313
66093,Glia,EEC N,NCAM1,CACNA1C,61.963900,0.0,0.044385,0.927767
79506,EEC S,Glia,MDK,PTPRZ1,56.294075,0.0,0.043247,0.926757
82730,EEC Enterochromaffin (EC),Glia,MDK,PTPRZ1,55.183800,0.0,0.041739,0.925544
97068,EEC N,Glia,MDK,PTPRZ1,50.526900,0.0,0.035418,0.919683
100154,EEC L,Glia,TTR,NGFR,49.391304,0.0,0.114665,0.917962
76734,Glia,EEC Enterochromaffin (EC),L1CAM,ERBB3,57.424440,0.0,0.044349,0.914813
79321,Glia,EEC L,L1CAM,ERBB3,56.380653,0.0,0.040639,0.911346
118868,EEC S,Glia,RTN4,NGFR,44.340492,0.0,0.012266,0.909349
81436,Glia,EEC N,L1CAM,ERBB3,55.604620,0.0,0.037880,0.908465
81647,Glia,EEC S,L1CAM,ERBB3,55.533650,0.0,0.037628,0.908187
84110,Glia,Enteroendocrine Cells (EEC),L1CAM,ERBB3,54.734560,0.0,0.034787,0.904861
91166,Glia,Enteroendocrine Cells (EEC),NCAM1,PTPRA,52.197480,0.0,0.007731,0.898007
149730,EEC L,Glia,RTN4,NGFR,38.121513,0.0,0.008577,0.893486
94049,Glia,EEC L,NCAM1,CACNA1C,51.224140,0.0,0.018512,0.892414

=== BEST4 Enterocyte <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
15924,Glia,BEST4 Enterocytes,S100A10,CFTR,135.516400,0.000,0.005989,0.960203
17111,BEST4 Enterocytes,Glia,LGALS3,MCAM,130.757870,0.000,0.002839,0.944833
10201,Glia,BEST4 Enterocytes,LGALS1,ITGB1,171.238750,0.000,0.000366,0.943912
39973,BEST4 Enterocytes,Glia,HLA-A,APLP2,81.691240,0.999,0.000203,0.939590
55926,Glia,BEST4 Enterocytes,APP,NOTCH2,68.044690,0.000,0.006934,0.939116
63684,BEST4 Enterocytes,Glia,MDK,PTPRZ1,63.425920,0.000,0.052928,0.933325
31457,Glia,BEST4 Enterocytes,HLA-A,APLP2,95.181500,0.000,0.000148,0.929915
65648,Glia,BEST4 Enterocytes,L1CAM,CD9,62.264435,0.000,0.013137,0.926749
78580,Glia,BEST4 Enterocytes,APP,CD74,56.737710,1.000,0.000088,0.926070
81011,Glia,BEST4 Enterocytes,MDK,NOTCH2,55.798070,0.000,0.005645,0.925489
37182,Glia,BEST4 Enterocytes,S100A4,ERBB3,85.506860,0.000,0.001028,0.919159
95352,Glia,BEST4 Enterocytes,TIMP1,CD63,50.886147,0.000,0.000114,0.915338
100143,BEST4 Enterocytes,Glia,MDK,NCL,49.393692,0.000,0.000476,0.901322
79285,Glia,BEST4 Enterocytes,ANXA1,ADRA2A,56.396782,0.000,0.007168,0.897209
88713,Glia,BEST4 Enterocytes,L1CAM,ERBB3,53.072060,0.000,0.028877,0.896539

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
63684,BEST4 Enterocytes,Glia,MDK,PTPRZ1,63.425920,0.0,0.052928,0.933325
65648,Glia,BEST4 Enterocytes,L1CAM,CD9,62.264435,0.0,0.013137,0.926749
79285,Glia,BEST4 Enterocytes,ANXA1,ADRA2A,56.396782,0.0,0.007168,0.897209
88713,Glia,BEST4 Enterocytes,L1CAM,ERBB3,53.072060,0.0,0.028877,0.896539
128420,Glia,BEST4 Enterocytes,APP,ADRA2A,42.426586,0.0,0.009769,0.880586
189403,BEST4 Enterocytes,Glia,RTN4,NGFR,32.953110,0.0,0.005512,0.870538
197476,BEST4 Enterocytes,Glia,APP,NGFR,32.107490,0.0,0.007133,0.865065
190707,BEST4 Enterocytes,Glia,CALM1,PTPRA,32.788013,1.0,0.000160,0.860431
105799,Glia,BEST4 Enterocytes,NCAM1,ROBO1,47.730667,0.0,0.011838,0.859660
298867,Glia,BEST4 Enterocytes,ARF1,CHRM3,24.627087,0.0,0.002491,0.848118
104486,Glia,BEST4 Enterocytes,L1CAM,ERBB2,48.026410,0.0,0.026361,0.842113
109563,Glia,BEST4 Enterocytes,NCAM1,PTPRA,46.712574,0.0,0.002833,0.842016
161584,Glia,BEST4 Enterocytes,CALM1,PTPRA,36.386670,1.0,0.000091,0.823167
379454,Glia,BEST4 Enterocytes,SLIT2,APP,20.806250,0.0,0.001606,0.822492
378971,Glia,BEST4 Enterocytes,GNAI2,ADRA2A,20.826132,0.0,0.003542,0.819672
165664,Glia,BEST4 Enterocytes,CNTN1,NOTCH2,35.828735,0.0,0.025847,0.808813
109776,Glia,BEST4 Enterocytes,L1CAM,EGFR,46.651608,0.0,0.010287,0.798681
273791,BEST4 Enterocytes,Glia,NTS,NGFR,25.999306,0.0,0.000602,0.771328
111695,Glia,BEST4 Enterocytes,L1CAM,EPHB2,46.101520,0.0,0.008341,0.765480
529723,Glia,BEST4 Enterocytes,SLIT2,ROBO1,16.550330,0.0,0.005213,0.765461

=== BEST4 Colonocytes <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
10089,Glia,BEST4 Colonocytes,LGALS1,ITGB1,172.382050,0.000,0.000415,0.947174
21006,Glia,BEST4 Colonocytes,S100A10,CFTR,119.752980,0.000,0.002330,0.937688
29111,BEST4 Colonocytes,Glia,LGALS3,MCAM,100.604225,0.000,0.002118,0.936682
60864,Glia,BEST4 Colonocytes,L1CAM,CD9,64.891860,0.000,0.015131,0.931402
4431,Glia,BEST4 Colonocytes,VIM,CD44,276.980220,0.000,0.000117,0.927357
68613,BEST4 Colonocytes,Glia,HLA-A,APLP2,60.931267,1.000,0.000136,0.927204
32268,Glia,BEST4 Colonocytes,HLA-A,APLP2,93.426704,0.000,0.000122,0.923403
94972,BEST4 Colonocytes,Glia,MDK,PTPRZ1,50.992400,0.000,0.036049,0.920334
49829,Glia,BEST4 Colonocytes,LAMB2,RPSA,72.394110,0.000,0.001052,0.914927
98891,BEST4 Colonocytes,Glia,PLA2G2A,ITGB1,49.857525,0.000,0.000651,0.912131
99394,Glia,BEST4 Colonocytes,APP,CD74,49.687748,0.998,0.000060,0.911622
38469,Glia,BEST4 Colonocytes,S100A4,ERBB3,83.743700,0.000,0.000805,0.909589
113277,Glia,BEST4 Colonocytes,TIMP1,CD63,45.715557,0.000,0.000097,0.908794
110761,Glia,BEST4 Colonocytes,APP,NOTCH2,46.362484,0.000,0.002407,0.900864
104360,BEST4 Colonocytes,Glia,APP,CD74,48.062420,1.000,0.000046,0.900826

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
60864,Glia,BEST4 Colonocytes,L1CAM,CD9,64.891860,0.000,0.015131,0.931402
94972,BEST4 Colonocytes,Glia,MDK,PTPRZ1,50.992400,0.000,0.036049,0.920334
93703,Glia,BEST4 Colonocytes,L1CAM,ERBB3,51.308900,0.000,0.022609,0.884627
176430,BEST4 Colonocytes,Glia,APP,NGFR,34.413820,0.000,0.009080,0.878545
165722,BEST4 Colonocytes,Glia,CALM1,PTPRA,35.819954,0.915,0.000179,0.867027
197869,BEST4 Colonocytes,Glia,RTN4,NGFR,32.058647,0.000,0.004981,0.864726
324616,Glia,BEST4 Colonocytes,SLIT2,APP,23.112574,0.000,0.002045,0.839436
110226,Glia,BEST4 Colonocytes,NCAM1,PTPRA,46.514230,0.000,0.002656,0.837674
105451,Glia,BEST4 Colonocytes,L1CAM,ERBB2,47.818480,0.000,0.024580,0.837407
106538,Glia,BEST4 Colonocytes,L1CAM,EPHB2,47.518715,0.000,0.018597,0.829754
94756,Glia,BEST4 Colonocytes,ANXA1,ADRA2A,51.044426,0.000,0.002113,0.825765
107470,Glia,BEST4 Colonocytes,L1CAM,EGFR,47.309666,0.000,0.014263,0.823677
162933,Glia,BEST4 Colonocytes,CALM1,PTPRA,36.188324,1.000,0.000085,0.818418
156244,Glia,BEST4 Colonocytes,APP,ADRA2A,37.074230,0.000,0.002880,0.800161
117213,Glia,BEST4 Colonocytes,NCAM1,ROBO1,44.742104,0.000,0.003395,0.766382
433605,Glia,BEST4 Colonocytes,PTN,NCL,19.096983,0.001,0.000204,0.746117
587552,Glia,BEST4 Colonocytes,ARF1,CHRM3,15.327206,0.000,0.000618,0.735563
839373,BEST4 Colonocytes,Glia,SPTAN1,PTPRA,11.637946,0.000,0.000221,0.719102
101250,Glia,BEST4 Colonocytes,LGALS1,PTPRC,162.964310,0.000,0.000004,0.713699
655298,Glia,BEST4 Colonocytes,CNTN1,NOTCH2,14.146529,0.000,0.008971,0.713658

=== Tuft <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
9236,Glia,Tuft Cells,LGALS1,ITGB1,181.628080,0.0,0.000815,0.961715
15654,Tuft Cells,Glia,HLA-A,APLP2,136.588040,0.0,0.000380,0.955106
53909,Tuft Cells,Glia,APP,CD74,69.381676,1.0,0.000138,0.940074
56656,Glia,Tuft Cells,L1CAM,CD9,67.554070,0.0,0.017150,0.935299
73896,Tuft Cells,Glia,RTN4,NGFR,58.618675,0.0,0.020736,0.928788
81150,Tuft Cells,Glia,APP,NGFR,55.733070,0.0,0.027084,0.925885
35942,Glia,Tuft Cells,S100A4,ERBB3,87.151260,0.0,0.001236,0.925749
32383,Glia,Tuft Cells,HLA-A,APLP2,93.158990,0.0,0.000118,0.922235
4454,Glia,Tuft Cells,VIM,CD44,276.299700,0.0,0.000090,0.917783
22041,Tuft Cells,Glia,AZGP1,ITGAV,117.490790,0.0,0.017654,0.916273
19668,Tuft Cells,Glia,HLA-A,ERBB2,122.549220,0.0,0.000753,0.913715
110113,Tuft Cells,Glia,MDK,PTPRZ1,46.549540,0.0,0.030018,0.913359
108994,Glia,Tuft Cells,TIMP1,CD63,46.879550,0.0,0.000101,0.910403
69070,Glia,Tuft Cells,PSAP,SORT1,60.698494,0.0,0.001913,0.906984
84142,Glia,Tuft Cells,L1CAM,ERBB3,54.716457,0.0,0.034723,0.904782

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
56656,Glia,Tuft Cells,L1CAM,CD9,67.554070,0.000,0.017150,0.935299
73896,Tuft Cells,Glia,RTN4,NGFR,58.618675,0.000,0.020736,0.928788
81150,Tuft Cells,Glia,APP,NGFR,55.733070,0.000,0.027084,0.925885
110113,Tuft Cells,Glia,MDK,PTPRZ1,46.549540,0.000,0.030018,0.913359
84142,Glia,Tuft Cells,L1CAM,ERBB3,54.716457,0.000,0.034723,0.904782
10818,Glia,Tuft Cells,LGALS1,PTPRC,165.374310,0.000,0.000054,0.903116
118459,Glia,Tuft Cells,SLIT2,APP,44.431830,0.000,0.006099,0.900290
98997,Glia,Tuft Cells,NCAM1,PTPRA,49.828255,0.000,0.005616,0.882404
92988,Glia,Tuft Cells,SDC2,PTPRJ,51.570220,0.000,0.001711,0.871694
142305,Glia,Tuft Cells,CALM1,PTPRA,39.502350,0.392,0.000181,0.867616
97410,Glia,Tuft Cells,THBS1,PTPRJ,50.455580,0.000,0.001428,0.856172
103301,Glia,Tuft Cells,L1CAM,EPHB2,48.362545,0.000,0.024703,0.848883
271855,Tuft Cells,Glia,CALM1,PTPRA,26.114614,1.000,0.000118,0.841251
230799,Tuft Cells,Glia,NCAM1,PTPRZ1,29.130184,0.000,0.033221,0.829252
243540,Tuft Cells,Glia,NTS,NGFR,28.110357,0.000,0.001146,0.823102
102396,Tuft Cells,Glia,NRTN,GFRA3,48.643250,0.000,0.239487,0.812849
153704,Tuft Cells,Glia,RTN4,TNFRSF19,37.447994,0.000,0.005723,0.808847
384023,Tuft Cells,Glia,NCAM1,NCAM2,20.671360,0.000,0.023843,0.797040
98055,Glia,Tuft Cells,ANXA1,GRM7,50.198124,0.000,0.002545,0.788906
175086,Glia,Tuft Cells,CALM1,GRM7,34.605830,0.911,0.000913,0.755081

=== EEC Progenitors <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
4164,Glia,EEC Progenitors,VIM,CD44,284.031100,0.000,0.000404,0.959470
10051,Glia,EEC Progenitors,LGALS1,ITGB1,172.691310,0.000,0.000429,0.947962
49135,EEC Progenitors,Glia,MDK,PTPRZ1,73.052650,0.000,0.065997,0.939871
18200,Glia,EEC Progenitors,SPP1,CD44,126.379980,0.000,0.007168,0.939135
70018,EEC Progenitors,Glia,NTS,NGFR,60.207787,0.000,0.009411,0.930244
31947,Glia,EEC Progenitors,TIMP3,CD44,94.120010,0.000,0.000740,0.929175
74048,EEC Progenitors,Glia,HLA-A,APLP2,58.539284,1.000,0.000128,0.925213
40547,Glia,EEC Progenitors,COL1A2,CD44,80.901150,0.000,0.000452,0.923344
37781,Glia,EEC Progenitors,S100A4,ERBB3,84.808590,0.000,0.000940,0.915756
56207,Glia,EEC Progenitors,LAMB2,RPSA,67.900510,0.000,0.000978,0.912029
72910,EEC Progenitors,Glia,MDK,NCL,59.020424,0.000,0.000594,0.910710
106031,Glia,EEC Progenitors,APP,CD74,47.667640,1.000,0.000052,0.905552
130249,Glia,EEC Progenitors,MDK,NCL,42.052155,0.000,0.000516,0.904842
127810,Glia,EEC Progenitors,TIMP1,CD63,42.525093,0.000,0.000086,0.903877
11883,EEC Progenitors,Glia,TFF3,ACKR3,158.626630,0.011,0.000841,0.900593

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
49135,EEC Progenitors,Glia,MDK,PTPRZ1,73.052650,0.000,0.065997,0.939871
70018,EEC Progenitors,Glia,NTS,NGFR,60.207787,0.000,0.009411,0.930244
86928,Glia,EEC Progenitors,L1CAM,CD9,53.778843,0.000,0.006699,0.900345
90665,Glia,EEC Progenitors,L1CAM,ERBB3,52.373790,0.000,0.026395,0.892296
121080,EEC Progenitors,Glia,CALM1,PTPRA,43.818913,0.000,0.000229,0.880616
176029,EEC Progenitors,Glia,RTN4,NGFR,34.474640,0.000,0.006414,0.878846
97458,Glia,EEC Progenitors,L1CAM,EPHB2,50.436836,0.000,0.039715,0.876885
186841,EEC Progenitors,Glia,APP,NGFR,33.231304,0.000,0.008082,0.872191
107159,Glia,EEC Progenitors,NCAM1,PTPRA,47.368870,0.000,0.003419,0.854124
156447,Glia,EEC Progenitors,CALM1,PTPRA,37.042965,0.998,0.000110,0.836440
349389,Glia,EEC Progenitors,SLIT2,APP,21.930061,0.000,0.001820,0.831428
245935,EEC Progenitors,Glia,TTR,NGFR,27.915730,0.000,0.018960,0.819822
114658,Glia,EEC Progenitors,NCAM1,CACNA1C,45.348800,0.000,0.004357,0.800964
111402,Glia,EEC Progenitors,L1CAM,ERBB2,46.194977,0.000,0.010673,0.772406
111621,Glia,EEC Progenitors,L1CAM,EGFR,46.123978,0.000,0.007099,0.767208
347795,Glia,EEC Progenitors,PTN,NCL,21.998070,0.000,0.000240,0.761100
118036,Glia,EEC Progenitors,NCAM1,GFRA1,44.532585,0.000,0.008092,0.748799
118805,Glia,EEC Progenitors,NCAM1,ROBO1,44.359600,0.000,0.002315,0.730358
864703,EEC Progenitors,Glia,RARRES1,NRP2,11.360714,0.000,0.000620,0.711747
895893,Glia,EEC Progenitors,SPTAN1,PTPRA,11.044399,0.000,0.000192,0.704458

=== Tuft Progenitors <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
10046,Glia,Tuft Progenitors,LGALS1,ITGB1,172.727860,0.000,0.000430,0.948052
4348,Glia,Tuft Progenitors,VIM,CD44,279.510740,0.000,0.000220,0.945893
40258,Tuft Progenitors,Glia,HLA-A,APLP2,81.292270,0.890,0.000202,0.939409
36977,Glia,Tuft Progenitors,S100A4,ERBB3,85.857080,0.000,0.001072,0.920713
87295,Glia,Tuft Progenitors,APP,CD74,53.626915,1.000,0.000076,0.920652
32624,Glia,Tuft Progenitors,HLA-A,APLP2,92.715000,0.000,0.000111,0.920172
72408,Glia,Tuft Progenitors,L1CAM,CD9,59.251392,0.000,0.010851,0.919990
19947,Glia,Tuft Progenitors,SPP1,CD44,121.859620,0.000,0.003909,0.919318
23438,Tuft Progenitors,Glia,APOA1,LRP1,113.764470,0.628,0.001050,0.918308
23440,Tuft Progenitors,Glia,APOA1,ABCA1,113.761370,0.615,0.001217,0.918288
103208,Tuft Progenitors,Glia,MDK,PTPRZ1,48.397156,0.000,0.032526,0.916482
95507,Tuft Progenitors,Glia,LGALS3,MCAM,50.856216,0.000,0.000929,0.907371
99378,Tuft Progenitors,Glia,APP,CD74,49.694283,1.000,0.000053,0.906961
34430,Glia,Tuft Progenitors,TIMP3,CD44,89.599650,0.000,0.000403,0.906438
83402,Glia,Tuft Progenitors,LAMB2,RPSA,55.021090,0.211,0.000764,0.901645

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
72408,Glia,Tuft Progenitors,L1CAM,CD9,59.251392,0.000,0.010851,0.919990
103208,Tuft Progenitors,Glia,MDK,PTPRZ1,48.397156,0.000,0.032526,0.916482
138023,Tuft Progenitors,Glia,RTN4,NGFR,40.331720,0.000,0.009888,0.900067
87779,Glia,Tuft Progenitors,L1CAM,ERBB3,53.422280,0.000,0.030122,0.898480
163787,Tuft Progenitors,Glia,APP,NGFR,36.045677,0.000,0.010458,0.885884
144075,Tuft Progenitors,Glia,CALM1,PTPRA,39.106250,0.541,0.000199,0.873175
98955,Glia,Tuft Progenitors,L1CAM,EPHB2,49.838850,0.000,0.035387,0.870521
107735,Glia,Tuft Progenitors,NCAM1,PTPRA,47.245100,0.000,0.003309,0.852065
296621,Glia,Tuft Progenitors,SLIT2,APP,24.744436,0.000,0.002355,0.848731
157229,Glia,Tuft Progenitors,CALM1,PTPRA,36.919193,0.999,0.000106,0.834179
24175,Glia,Tuft Progenitors,LGALS1,PTPRC,163.528630,0.000,0.000016,0.833626
107805,Glia,Tuft Progenitors,L1CAM,ERBB2,47.222510,0.000,0.019475,0.820929
257155,Tuft Progenitors,Glia,NTS,NGFR,27.145756,0.000,0.000897,0.804604
110574,Glia,Tuft Progenitors,L1CAM,EGFR,46.414370,0.000,0.008853,0.786346
117614,Glia,Tuft Progenitors,NCAM1,ROBO1,44.630993,0.000,0.003081,0.757587
667745,Glia,Tuft Progenitors,SDC2,PTPRJ,13.943405,0.000,0.000334,0.750257
431802,Tuft Progenitors,Glia,RTN4,TNFRSF19,19.161041,0.000,0.002729,0.745033
453949,Glia,Tuft Progenitors,PTN,NCL,18.474104,0.000,0.000197,0.742469
741448,Glia,Tuft Progenitors,THBS1,PTPRJ,12.828764,0.000,0.000279,0.724683
605273,Glia,Tuft Progenitors,SLIT2,SDC1,15.004214,0.000,0.004852,0.721650

=== Secretory Progenitors <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
4245,Glia,Secretory Progenitors,VIM,CD44,282.581730,0.00,0.000345,0.956293
10425,Glia,Secretory Progenitors,LGALS1,ITGB1,169.238830,0.00,0.000279,0.936330
18745,Glia,Secretory Progenitors,SPP1,CD44,124.930626,0.00,0.006123,0.934473
2275,Secretory Progenitors,Glia,TFF3,ACKR3,388.699130,0.00,0.002082,0.934428
63877,Glia,Secretory Progenitors,L1CAM,CD9,63.298590,0.00,0.013922,0.928694
80002,Secretory Progenitors,Glia,PLA2G2A,ITGB1,56.118183,0.00,0.000921,0.925104
32652,Glia,Secretory Progenitors,TIMP3,CD44,92.670654,0.00,0.000632,0.923812
79009,Secretory Progenitors,Glia,HLA-A,APLP2,56.522934,1.00,0.000122,0.923398
44348,Glia,Secretory Progenitors,LAMB2,RPSA,77.426010,0.00,0.001135,0.917846
41961,Glia,Secretory Progenitors,COL1A2,CD44,79.451800,0.00,0.000386,0.917578
69625,Secretory Progenitors,Glia,LGALS3,MCAM,60.399956,0.00,0.001157,0.916199
107861,Secretory Progenitors,Glia,PLA2G2A,ERBB3,47.205414,0.00,0.003010,0.914188
101913,Glia,Secretory Progenitors,APP,CD74,48.808870,1.00,0.000056,0.909134
33869,Glia,Secretory Progenitors,HLA-A,APLP2,90.450930,0.01,0.000078,0.906154
39026,Glia,Secretory Progenitors,S100A4,ERBB3,82.842545,0.00,0.000691,0.903106

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
63877,Glia,Secretory Progenitors,L1CAM,CD9,63.298590,0.0,0.013922,0.928694
138877,Secretory Progenitors,Glia,MDK,PTPRZ1,40.170876,0.0,0.021359,0.898911
95615,Glia,Secretory Progenitors,L1CAM,EPHB2,50.831860,0.0,0.042574,0.880588
97560,Glia,Secretory Progenitors,L1CAM,ERBB3,50.407745,0.0,0.019405,0.876598
192583,Secretory Progenitors,Glia,APP,NGFR,32.569927,0.0,0.007523,0.868146
193047,Secretory Progenitors,Glia,RTN4,NGFR,32.526947,0.0,0.005259,0.867869
167498,Secretory Progenitors,Glia,CALM1,PTPRA,35.626700,1.0,0.000178,0.866636
366290,Glia,Secretory Progenitors,SLIT2,APP,21.268684,0.0,0.001694,0.826350
107718,Glia,Secretory Progenitors,L1CAM,ERBB2,47.253517,0.0,0.019740,0.821922
108245,Glia,Secretory Progenitors,L1CAM,EGFR,47.103233,0.0,0.013015,0.816933
113294,Glia,Secretory Progenitors,NCAM1,PTPRA,45.708633,0.0,0.001936,0.815034
169389,Glia,Secretory Progenitors,CALM1,PTPRA,35.382730,1.0,0.000062,0.793755
110340,Glia,Secretory Progenitors,L1CAM,FGFR2,46.471603,0.0,0.025394,0.789547
115905,Glia,Secretory Progenitors,NCAM1,FGFR2,45.062855,0.0,0.010121,0.786890
399259,Glia,Secretory Progenitors,PTN,NCL,20.164223,0.0,0.000218,0.751986
118174,Glia,Secretory Progenitors,NCAM1,ROBO1,44.495106,0.0,0.002697,0.745160
579821,Glia,Secretory Progenitors,SLIT2,SDC1,15.472715,0.0,0.005712,0.737733
1000273,Glia,Secretory Progenitors,NID1,PTPRF,10.141778,0.0,0.000448,0.691389
1051210,Secretory Progenitors,Glia,RARRES1,NRP2,9.803700,0.0,0.000487,0.686525
823157,Secretory Progenitors,Glia,CDH1,PTPRF,11.821907,0.0,0.000266,0.681938

=== Villus-bottom enterocytes <-> Glia ===
n interactions: 8916

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
10237,Glia,Lower Villus Enterocytes,LGALS1,ITGB1,170.820420,0.0,0.000348,0.942554
20931,Lower Villus Enterocytes,Glia,LGALS3,MCAM,119.828500,0.0,0.002578,0.942262
69644,Lower Villus Enterocytes,Glia,HLA-A,APLP2,60.391937,1.0,0.000134,0.926770
32020,Glia,Lower Villus Enterocytes,HLA-A,APLP2,93.957140,0.0,0.000130,0.925565
72061,Glia,Lower Villus Enterocytes,L1CAM,CD9,59.434845,0.0,0.010990,0.920458
88871,Glia,Lower Villus Enterocytes,APP,CD74,53.013763,1.0,0.000073,0.919432
37178,Glia,Lower Villus Enterocytes,S100A4,ERBB3,85.511520,0.0,0.001029,0.919180
22933,Glia,Lower Villus Enterocytes,S100A10,CFTR,115.045500,0.0,0.001237,0.916423
4460,Glia,Lower Villus Enterocytes,VIM,CD44,276.150820,0.0,0.000084,0.915114
63134,Glia,Lower Villus Enterocytes,LAMB2,RPSA,63.793526,0.0,0.000910,0.909093
109500,Lower Villus Enterocytes,Glia,LGALS3BP,ITGB1,46.725570,0.0,0.000615,0.902325
72623,Lower Villus Enterocytes,Glia,CALM1,PTPRA,59.165230,0.0,0.000325,0.897836
88698,Glia,Lower Villus Enterocytes,L1CAM,ERBB3,53.076720,0.0,0.028893,0.896566
34702,Glia,Lower Villus Enterocytes,HLA-A,ERBB2,89.185390,0.0,0.000477,0.893964
153443,Glia,Lower Villus Enterocytes,MDK,NCL,37.496060,0.0,0.000395,0.892724

  neuro/axon keyword hits: 2125

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
72061,Glia,Lower Villus Enterocytes,L1CAM,CD9,59.434845,0.0,0.010990,0.920458
72623,Lower Villus Enterocytes,Glia,CALM1,PTPRA,59.165230,0.0,0.000325,0.897836
88698,Glia,Lower Villus Enterocytes,L1CAM,ERBB3,53.076720,0.0,0.028893,0.896566
158214,Lower Villus Enterocytes,Glia,RTN4,NGFR,36.780148,0.0,0.007782,0.888764
203329,Lower Villus Enterocytes,Glia,APP,NGFR,31.512733,0.0,0.006630,0.860746
101333,Glia,Lower Villus Enterocytes,L1CAM,ERBB2,49.009052,0.0,0.034778,0.859675
112877,Glia,Lower Villus Enterocytes,NCAM1,PTPRA,45.801647,0.0,0.002020,0.818179
397836,Glia,Lower Villus Enterocytes,SLIT2,APP,20.211490,0.0,0.001493,0.817099
108549,Glia,Lower Villus Enterocytes,L1CAM,EPHB2,47.010246,0.0,0.014917,0.813611
109508,Glia,Lower Villus Enterocytes,L1CAM,EGFR,46.723630,0.0,0.010722,0.801991
168563,Glia,Lower Villus Enterocytes,CALM1,PTPRA,35.475742,1.0,0.000065,0.797171
252571,Lower Villus Enterocytes,Glia,MDK,PTPRZ1,27.483343,0.0,0.004135,0.796450
99278,Glia,Lower Villus Enterocytes,ANXA1,ADRA2A,49.724920,0.0,0.000867,0.752227
491392,Glia,Lower Villus Enterocytes,PTN,NCL,17.441977,0.0,0.000184,0.736016
118713,Glia,Lower Villus Enterocytes,NCAM1,ROBO1,44.393590,0.0,0.002411,0.734341
573386,Lower Villus Enterocytes,Glia,RTN4,TNFRSF19,15.609467,0.0,0.002148,0.721618
166276,Glia,Lower Villus Enterocytes,APP,ADRA2A,35.754723,0.0,0.001182,0.719488
612073,Glia,Lower Villus Enterocytes,SLIT2,SDC1,14.877275,0.0,0.004619,0.716682
883810,Lower Villus Enterocytes,Glia,SPTAN1,PTPRA,11.159107,0.0,0.000197,0.707340
666473,Lower Villus Enterocytes,Glia,CDH1,PTPRF,13.967814,0.0,0.000327,0.703688

### 2.2 Glia ↔ EEC neuropod focus: NCAM, GDNF / RET / GFRα L–R, neurofilament

**Context:** Recent 3D microscopy / ultrastructure work reports direct glial contacts on EEC neuropods (including **NCAM**-related adhesion). **GLP-1 / EEC L** populations are enriched **distally** (ileum, some colon); **CCK / EEC I** may enrich more **proximally**. The precomputed table here is **`ileum_corrected_liana.csv`** (ileum-centric CCC); use it to see if overlapping **L–R** signal appears for **Glia ↔ EEC L** vs **Glia ↔ EEC I (CCK+)**. Colon- or duodenum-specific CCC would need separate LIANA outputs.

This block:
1. **Filters** Glia↔EEC L and Glia↔EEC I tables for curated **token sets** (NCAM / IgCAM; **GDNF-family ligands** (**GDNF**, **NRTN**, **ARTN**, **PSPN**) plus **RET** and **GFRA1–4** co-receptors; **neurofilament** genes if they appear as L–R in consensus).
2. Writes **`neuropod_glia_eec_focus_summary.csv`** (top hits per panel) and bar PDFs under `FIG_DIR`.
3. Optionally **mean `log1p` expression** of **NEFL / NEFM / NEFH / NCAM1 / GDNF / RET / GFRA1** in EEC subsets vs other epithelial types (ileum vs duodenum/jejunum vs colon from `tissue_ontology_term`), using the integrated object in **backed** mode (slow on first run).

In [ ]:
# --- Curated tokens: NCAM/neuropod adhesion; GDNF-family + RET/GFRa; neurofilament ---
# (Substring match on ligand_complex | receptor_complex, uppercase; extend as needed.)
NEUROPOD_NCAM_IGCAM_TOKENS = {
    "NCAM1", "NCAM2", "NCAML1", "L1CAM", "CHL1", "DSCAM", "OPCML", "PTPRF",
    "CADM1", "CADM2", "CADM3", "NRXN", "NLGN", "CNTN", "LRRTM", "LRRC4",
}
NEUROPOD_GDNF_RET_GFRA_TOKENS = {
    "GDNF",
    "NRTN",
    "ARTN",
    "PSPN",
    "RET",
    "GFRA1",
    "GFRA2",
    "GFRA3",
    "GFRA4",
}
NEUROPOD_NEUROFIL_TOKENS = {"NEFL", "NEFM", "NEFH", "PRPH", "INA"}


def _lr_upper_concat(df: pd.DataFrame) -> pd.Series:
    return (
        df["ligand_complex"].astype(str) + "|" + df["receptor_complex"].astype(str)
    ).str.upper()


def mask_lr_token_hits(df: pd.DataFrame, tokens: set[str]) -> pd.Series:
    lr = _lr_upper_concat(df)
    pat = "|".join(re.escape(t) for t in sorted(tokens))
    return lr.str.contains(pat, regex=True, na=False)


def filter_glia_eec_neuropod_focus(
    table: pd.DataFrame,
    *,
    name: str,
    token_set: set[str],
    set_label: str,
) -> pd.DataFrame:
    if table is None or table.empty:
        return pd.DataFrame()
    m = bidirectional_mask(table, EEC_L | EEC_I | EEC_MAT, GLIA)
    sub = table.loc[m].copy()
    sub = sub[mask_lr_token_hits(sub, token_set)]
    if sub.empty:
        return sub
    sub = sub.assign(context=name, gene_set=set_label)
    return sub.sort_values("lrscore", ascending=False)


def export_neuropod_focus_tables() -> pd.DataFrame:
    rows_out = []
    eec_keys = ("EEC L <-> Glia", "EEC I (CCK+) <-> Glia")
    focus_spec = (
        ("NCAM_IgCAM", NEUROPOD_NCAM_IGCAM_TOKENS),
        ("GDNF_RET_GFRA", NEUROPOD_GDNF_RET_GFRA_TOKENS),
        ("neurofilament", NEUROPOD_NEUROFIL_TOKENS),
    )
    for gkey in eec_keys:
        base = glia_tables.get(gkey)
        if base is None or base.empty:
            print(f"  skip focus: empty glia_tables['{gkey}']")
            continue
        for tag, tok in focus_spec:
            hit = filter_glia_eec_neuropod_focus(base, name=gkey, token_set=tok, set_label=tag)
            if hit.empty:
                print(f"  no hits: {gkey} / {tag}")
                continue
            top = hit.head(25).copy()
            rows_out.append(top)
            fig, ax = plt.subplots(figsize=(5.5, 4.2))
            hbar_top_lr(top, ax, title=f"{gkey}: {tag} (top 10)", n=10)
            panel_label(ax, "")
            fig.tight_layout(pad=0.6)
            safe = gkey.replace(" ", "_").replace("(", "").replace(")", "").replace("+", "p")
            save_pdf(fig, FIG_DIR / f"fig_neuropod_glia_{safe}_{tag}.pdf")
    if not rows_out:
        return pd.DataFrame()
    comb = pd.concat(rows_out, ignore_index=True)
    outp = FIG_DIR / "neuropod_glia_eec_focus_summary.csv"
    outp.parent.mkdir(parents=True, exist_ok=True)
    comb.to_csv(outp, index=False)
    print("Wrote", outp, "rows", len(comb))
    return comb


_neu_df = export_neuropod_focus_tables()
if _neu_df is not None and len(_neu_df):
    display(_neu_df.head(40))


# --- Optional: neurofilament + NCAM1 mean log1p by EEC type and broad tissue region ---
def _tissue_bucket(s: str) -> str:
    t = str(s).lower()
    if "ileum" in t:
        return "ileum"
    if "colon" in t:
        return "colon"
    if any(x in t for x in ("duoden", "jejun", "stomach", "fundus", "pylor")):
        return "proximal_gut"
    return "other"


def plot_neurofil_ncam_expr_by_eec(
    genes: tuple[str, ...] = ("NEFL", "NEFM", "NEFH", "NCAM1", "GDNF", "RET", "GFRA1"),
    max_cells_per_stratum: int = 4000,
) -> None:
    if not INTEGRATED.is_file():
        print("INTEGRATED h5ad missing; skip expression panel")
        return
    try:
        ad = sc.read_h5ad(INTEGRATED, backed="r")
    except Exception as e:
        print("Could not open INTEGRATED:", e)
        return
    obs = ad.obs
    ct = obs["hgca_celltype_v1"].astype(str)
    tissue_col = "tissue_ontology_term" if "tissue_ontology_term" in obs.columns else None
    eec_types = sorted(set(EEC_MAT) | EEC_L | EEC_I)
    mask_epi = ct.isin(eec_types) | (
        ct.str.contains("Enterocyte", case=False, na=False)
        & ~ct.str.contains("Progenitor", case=False, na=False)
    )
    mask_glia = ct.eq("Glia")
    mask_plot = mask_epi | mask_glia
    if not mask_plot.any():
        print("No EEC/enterocyte/glia cells found for expression panel")
        return
    # gene names: prefer var['gene_symbol'] if present
    gsym = None
    if "gene_symbol" in ad.var.columns:
        gsym = ad.var["gene_symbol"].astype(str).values
    var_names = np.array(ad.var_names.astype(str))
    def _gene_idx(g: str):
        if gsym is not None:
            jj = np.flatnonzero(gsym == g)
            if len(jj):
                return int(jj[0])
        jj = np.flatnonzero(var_names == g)
        return int(jj[0]) if len(jj) else None

    idxs = {g: _gene_idx(g) for g in genes}
    missing = [g for g, j in idxs.items() if j is None]
    if missing:
        print("Missing genes in object (skipped):", missing)
    idxs = {g: j for g, j in idxs.items() if j is not None}
    if not idxs:
        return

    sub_idx = np.flatnonzero(mask_plot.to_numpy())
    if len(sub_idx) > max_cells_per_stratum:
        rng = np.random.default_rng(0)
        sub_idx = rng.choice(sub_idx, size=max_cells_per_stratum, replace=False)
        sub_idx = np.sort(sub_idx)

    want_names = [ad.var_names[j] for j in idxs.values()]
    Xchunk = ad[sub_idx, want_names].X
    if hasattr(Xchunk, "toarray"):
        Xchunk = Xchunk.toarray()
    mat = np.asarray(Xchunk, dtype=float)
    sub_obs = obs.iloc[sub_idx].copy()
    sub_obs = sub_obs.assign(
        broad_region=sub_obs[tissue_col].map(_tissue_bucket) if tissue_col else "all",
        cell_group=ct.iloc[sub_idx].astype(str),
    )
    for i, (gn, col_j) in enumerate(zip(idxs.keys(), range(mat.shape[1]))):
        sub_obs[gn] = np.log1p(mat[:, col_j])

    # Aggregate: EEC I vs EEC L vs Glia vs enterocyte (non-EEC)
    rows = []
    for (region, cgroup), gg in sub_obs.groupby(["broad_region", "cell_group"], sort=False):
        chunk = {g: float(gg[g].mean()) for g in idxs}
        rows.append({"broad_region": region, "cell_group": cgroup, "n_cells": len(gg), **chunk})
    agg = pd.DataFrame(rows).sort_values(["broad_region", "cell_group"])
    tout = FIG_DIR / "neurofil_ncam_mean_log1p_by_celltype_region.csv"
    agg.to_csv(tout, index=False)
    print("Wrote", tout)

    # Small multi-panel bar: EEC L vs EEC I in ileum for each gene
    ile = agg[agg["broad_region"].eq("ileum")]
    focus = ile[ile["cell_group"].isin(["EEC L", "EEC I Cells (CCK+)", "EEC I", "Glia"])].copy()
    if focus.empty:
        print("No ileum rows for EEC L / EEC I / Glia in expression summary")
        return
    fig, axes = plt.subplots(1, len(idxs), figsize=(2.2 * len(idxs), 3.2), constrained_layout=True)
    if len(idxs) == 1:
        axes = [axes]
    for ax, g in zip(axes, idxs):
        d = focus.pivot_table(index="cell_group", values=g, aggfunc="mean")
        d.plot(kind="barh", ax=ax, legend=False, color=NATURE_CYCLE[0])
        ax.set_title(g, fontsize=7)
        ax.set_xlabel("mean log1p expr")
    fig.suptitle("Ileum: mean log1p (subset of cells)", fontsize=7)
    save_pdf(fig, FIG_DIR / "fig_neuropod_neurofil_ncam_expr_ileum_bars.pdf")


plot_neurofil_ncam_expr_by_eec()

### 2.2 Follicle-associated resident macrophages ↔ T subsets
Pairs include **CD4 Tr1**, **CD4 Tfr**, **CD4 Tfh**, **CD4 pTreg**, **CD4 Th17**, **CD4 tTreg**, **NKT Cells**, **Gamma Delta T Cells** (LIANA naming).

In [6]:
farm_tables = {}
for t in sorted(T_WITH_FARM):
    m = bidirectional_mask(dfw, FARM, {t})
    sub = dfw.loc[m].sort_values("lrscore", ascending=False)
    farm_tables[t] = sub
    print(f"\n=== FARM <-> {t} ===  n={len(sub)}")
    if len(sub):
        display(sub.head(12))
        na = sub[neuro_axon_mask(sub)]
        if len(na):
            print("  neuro/axon hits:")
            display(na.head(15))

=== FARM <-> CD4 Tfh ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
5111,Follicle Associated Resident Macrophages,CD4 Tfh,HLA-B,CD3D,250.954330,0.0,0.001132,0.979237
284,Follicle Associated Resident Macrophages,CD4 Tfh,HLA-DRA,CD4,737.163900,0.0,0.003098,0.973029
11371,Follicle Associated Resident Macrophages,CD4 Tfh,LGALS1,PTPRC,161.609570,0.0,0.000803,0.972883
2295,Follicle Associated Resident Macrophages,CD4 Tfh,HLA-DPA1,CD4,386.748080,0.0,0.003609,0.962949
2353,Follicle Associated Resident Macrophages,CD4 Tfh,HLA-DRB1,CD4,381.890600,0.0,0.003080,0.962718
24291,Follicle Associated Resident Macrophages,CD4 Tfh,LGALS1,CD69,111.552420,0.0,0.000544,0.961529
796,CD4 Tfh,Follicle Associated Resident Macrophages,COPA,CD74,812.396700,0.0,0.000640,0.959653
3168,Follicle Associated Resident Macrophages,CD4 Tfh,HLA-DPB1,CD4,322.042630,0.0,0.003073,0.959451
29060,Follicle Associated Resident Macrophages,CD4 Tfh,HMGB1,CXCR4,100.721054,0.0,0.000373,0.956796
1312,CD4 Tfh,Follicle Associated Resident Macrophages,APP,CD74,810.964000,0.0,0.000184,0.947623
1337,Follicle Associated Resident Macrophages,CD4 Tfh,HLA-DRA,LAG3,730.580200,0.0,0.001283,0.946679
10138,Follicle Associated Resident Macrophages,CD4 Tfh,HLA-DQA1,CD4,171.727050,0.0,0.003264,0.944652

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
11371,Follicle Associated Resident Macrophages,CD4 Tfh,LGALS1,PTPRC,161.609570,0.000,0.000803,0.972883
25025,Follicle Associated Resident Macrophages,CD4 Tfh,LGALS9,PTPRC,109.532196,0.000,0.001918,0.940010
27567,Follicle Associated Resident Macrophages,CD4 Tfh,MRC1,PTPRC,103.735000,0.000,0.002167,0.919246
245435,Follicle Associated Resident Macrophages,CD4 Tfh,CALM1,PTPRA,27.956272,1.000,0.000112,0.837456
204075,CD4 Tfh,Follicle Associated Resident Macrophages,CALM1,PTPRA,31.437893,1.000,0.000054,0.781293
217094,CD4 Tfh,Follicle Associated Resident Macrophages,LGALS1,PTPRC,30.251638,1.000,0.000003,0.699040
856283,CD4 Tfh,Follicle Associated Resident Macrophages,SEMA4D,PLXNB2,11.452521,0.000,0.000703,0.687619
218427,CD4 Tfh,Follicle Associated Resident Macrophages,LGALS9,PTPRC,30.122974,0.512,0.000036,0.682437
883303,CD4 Tfh,Follicle Associated Resident Macrophages,SEMA4D,CD72,11.164046,0.000,0.000977,0.675299
146133,Follicle Associated Resident Macrophages,CD4 Tfh,CD22,PTPRC,97.465120,0.000,0.000074,0.671316
1299185,Follicle Associated Resident Macrophages,CD4 Tfh,THBS1,PTPRJ,8.255569,0.000,0.000102,0.614574
1417809,CD4 Tfh,Follicle Associated Resident Macrophages,SPTAN1,PTPRA,7.665841,0.000,0.000082,0.608478
1182509,CD4 Tfh,Follicle Associated Resident Macrophages,VEGFB,NRP1,8.934482,0.000,0.000245,0.605826
283673,CD4 Tfh,Follicle Associated Resident Macrophages,HSPA8,ADRB2,25.459852,1.000,0.000094,0.593630
1101939,CD4 Tfh,Follicle Associated Resident Macrophages,GNAI2,UNC5B,9.436928,0.000,0.000165,0.576526

=== FARM <-> CD4 Tfr ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
4767,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-B,CD3D,264.465580,0.0,0.001409,0.981348
283,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-DRA,CD4,737.848200,0.0,0.003342,0.974007
11563,Follicle Associated Resident Macrophages,CD4 Tfr,LGALS1,PTPRC,160.503600,0.0,0.000794,0.972732
520,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-DRA,LAG3,733.703300,0.0,0.003187,0.965499
2289,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-DPA1,CD4,387.432400,0.0,0.003893,0.964278
2341,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-DRB1,CD4,382.574920,0.0,0.003323,0.964055
3142,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-DPB1,CD4,322.726960,0.0,0.003315,0.960901
750,CD4 Tfr,Follicle Associated Resident Macrophages,COPA,CD74,812.560670,0.0,0.000671,0.960555
28482,Follicle Associated Resident Macrophages,CD4 Tfr,LGALS1,CD69,101.839660,0.0,0.000432,0.957033
33770,Follicle Associated Resident Macrophages,CD4 Tfr,HMGB1,CXCR4,90.606926,0.0,0.000313,0.953008
2334,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-DPA1,LAG3,383.287500,0.0,0.003713,0.952741
2422,Follicle Associated Resident Macrophages,CD4 Tfr,HLA-DRB1,LAG3,378.430020,0.0,0.003169,0.952449

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
11563,Follicle Associated Resident Macrophages,CD4 Tfr,LGALS1,PTPRC,160.503600,0.000,0.000794,0.972732
25484,Follicle Associated Resident Macrophages,CD4 Tfr,LGALS9,PTPRC,108.426220,0.000,0.001896,0.939687
28066,Follicle Associated Resident Macrophages,CD4 Tfr,MRC1,PTPRC,102.629030,0.000,0.002142,0.918821
244322,Follicle Associated Resident Macrophages,CD4 Tfr,CALM1,PTPRA,28.046040,1.000,0.000113,0.838492
193225,CD4 Tfr,Follicle Associated Resident Macrophages,CALM1,PTPRA,32.508040,1.000,0.000056,0.784340
215319,CD4 Tfr,Follicle Associated Resident Macrophages,LGALS1,PTPRC,30.429136,1.000,0.000004,0.717750
217208,CD4 Tfr,Follicle Associated Resident Macrophages,LGALS9,PTPRC,30.242014,0.483,0.000042,0.697900
752865,Follicle Associated Resident Macrophages,CD4 Tfr,THBS1,PTPRJ,12.663293,0.000,0.000174,0.675269
147794,Follicle Associated Resident Macrophages,CD4 Tfr,CD22,PTPRC,96.359146,0.000,0.000074,0.670053
1015271,CD4 Tfr,Follicle Associated Resident Macrophages,SEMA4D,PLXNB2,10.038490,0.000,0.000590,0.668418
1058789,CD4 Tfr,Follicle Associated Resident Macrophages,SEMA4D,CD72,9.750015,0.000,0.000819,0.655720
1268684,CD4 Tfr,Follicle Associated Resident Macrophages,SPTAN1,PTPRA,8.431432,0.000,0.000093,0.623759
831710,Follicle Associated Resident Macrophages,CD4 Tfr,SDC2,PTPRJ,11.719798,0.000,0.000083,0.599915
896066,CD4 Tfr,Follicle Associated Resident Macrophages,GNAI2,UNC5B,11.042852,0.000,0.000197,0.597822
275078,CD4 Tfr,Follicle Associated Resident Macrophages,HSPA8,ADRB2,25.941484,0.952,0.000096,0.595926

=== FARM <-> CD4 Th17 ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
4913,Follicle Associated Resident Macrophages,CD4 Th17,HLA-B,CD3D,261.29250,0.0,0.001344,0.980911
12176,Follicle Associated Resident Macrophages,CD4 Th17,LGALS1,CD69,156.71900,0.0,0.001064,0.972194
17888,Follicle Associated Resident Macrophages,CD4 Th17,LGALS1,PTPRC,127.46047,0.0,0.000521,0.966555
589,Follicle Associated Resident Macrophages,CD4 Th17,HLA-DRA,CD4,733.17450,0.0,0.001676,0.963677
747,CD4 Th17,Follicle Associated Resident Macrophages,COPA,CD74,812.56920,0.0,0.000673,0.960600
760,Follicle Associated Resident Macrophages,CD4 Th17,HLA-DRA,LAG3,732.35610,0.0,0.002366,0.960175
3162,CD4 Th17,Follicle Associated Resident Macrophages,TNFSF13B,HLA-DPB1,322.37463,0.0,0.003688,0.960174
35185,Follicle Associated Resident Macrophages,CD4 Th17,HMGB1,CXCR4,88.44420,0.0,0.000300,0.952058
2338,Follicle Associated Resident Macrophages,CD4 Th17,HLA-DPA1,CD4,382.75873,0.0,0.001952,0.950281
2430,Follicle Associated Resident Macrophages,CD4 Th17,HLA-DRB1,CD4,377.90125,0.0,0.001666,0.949975
3258,Follicle Associated Resident Macrophages,CD4 Th17,HLA-DPB1,CD4,318.05328,0.0,0.001662,0.945654
2352,Follicle Associated Resident Macrophages,CD4 Th17,HLA-DPA1,LAG3,381.94030,0.0,0.002756,0.945560

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
17888,Follicle Associated Resident Macrophages,CD4 Th17,LGALS1,PTPRC,127.460470,0.00,0.000521,0.966555
46619,Follicle Associated Resident Macrophages,CD4 Th17,LGALS9,PTPRC,75.383095,0.00,0.001245,0.926590
53642,Follicle Associated Resident Macrophages,CD4 Th17,MRC1,PTPRC,69.585900,0.00,0.001406,0.901667
170848,CD4 Th17,Follicle Associated Resident Macrophages,LGALS1,PTPRC,35.166590,1.00,0.000022,0.855533
67252,CD4 Th17,Follicle Associated Resident Macrophages,CALM1,PTPRA,61.616870,0.00,0.000109,0.835765
260341,Follicle Associated Resident Macrophages,CD4 Th17,CALM1,PTPRA,26.921440,1.00,0.000092,0.823726
592841,Follicle Associated Resident Macrophages,CD4 Th17,RTN4,LINGO1,15.243607,0.00,0.000673,0.729560
218520,CD4 Th17,Follicle Associated Resident Macrophages,LGALS9,PTPRC,30.115297,0.51,0.000036,0.681343
152148,Follicle Associated Resident Macrophages,CD4 Th17,HSPA8,ADRB2,37.713920,0.00,0.000187,0.673054
1014808,CD4 Th17,Follicle Associated Resident Macrophages,VEGFB,NRP1,10.041990,0.00,0.000419,0.667843
175955,Follicle Associated Resident Macrophages,CD4 Th17,ARPC5,ADRB2,34.486510,0.00,0.000360,0.662980
181920,CD4 Th17,Follicle Associated Resident Macrophages,HSPA8,ADRB2,38.555397,0.00,0.000144,0.643203
238895,Follicle Associated Resident Macrophages,CD4 Th17,GNAS,ADRB2,28.457000,0.00,0.000173,0.640787
246696,Follicle Associated Resident Macrophages,CD4 Th17,IL1B,ADRB2,27.864439,0.00,0.000355,0.638313
212503,Follicle Associated Resident Macrophages,CD4 Th17,CD22,PTPRC,63.316020,0.00,0.000048,0.621963

=== FARM <-> CD4 Tr1 ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
4570,Follicle Associated Resident Macrophages,CD4 Tr1,HLA-B,CD3D,271.72162,0.0,0.001558,0.982244
269,Follicle Associated Resident Macrophages,CD4 Tr1,HLA-DRA,LAG3,742.08690,0.0,0.008300,0.978335
10504,Follicle Associated Resident Macrophages,CD4 Tr1,LGALS1,PTPRC,168.04349,0.0,0.000856,0.973715
2236,Follicle Associated Resident Macrophages,CD4 Tr1,HLA-DPA1,LAG3,391.67110,0.0,0.009668,0.970177
2293,Follicle Associated Resident Macrophages,CD4 Tr1,HLA-DRB1,LAG3,386.81363,0.0,0.008252,0.969989
3083,Follicle Associated Resident Macrophages,CD4 Tr1,HLA-DPB1,LAG3,326.96567,0.0,0.008232,0.967338
818,CD4 Tr1,Follicle Associated Resident Macrophages,COPA,CD74,812.31730,0.0,0.000625,0.959193
6742,CD4 Tr1,Follicle Associated Resident Macrophages,HLA-A,APLP2,216.95659,0.0,0.000428,0.957613
919,Follicle Associated Resident Macrophages,CD4 Tr1,HLA-DRA,CD4,731.61250,0.0,0.001119,0.955902
9692,Follicle Associated Resident Macrophages,CD4 Tr1,HLA-DQA1,LAG3,176.65010,0.0,0.008743,0.955283
976,Follicle Associated Resident Macrophages,CD4 Tr1,B2M,KLRD1,671.40390,0.0,0.000288,0.955238
30233,Follicle Associated Resident Macrophages,CD4 Tr1,LGALS1,CD69,98.00485,0.0,0.000388,0.954759

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
10504,Follicle Associated Resident Macrophages,CD4 Tr1,LGALS1,PTPRC,168.043490,0.000,0.000856,0.973715
22546,Follicle Associated Resident Macrophages,CD4 Tr1,LGALS9,PTPRC,115.966110,0.000,0.002045,0.941791
24773,Follicle Associated Resident Macrophages,CD4 Tr1,MRC1,PTPRC,110.168915,0.000,0.002310,0.921592
178571,CD4 Tr1,Follicle Associated Resident Macrophages,LGALS1,PTPRC,34.168556,1.000,0.000018,0.843488
245291,Follicle Associated Resident Macrophages,CD4 Tr1,CALM1,PTPRA,27.969378,1.000,0.000112,0.837608
78703,CD4 Tr1,Follicle Associated Resident Macrophages,CALM1,PTPRA,56.665870,0.000,0.000100,0.829715
216530,CD4 Tr1,Follicle Associated Resident Macrophages,LGALS9,PTPRC,30.312235,0.469,0.000045,0.705897
151497,Follicle Associated Resident Macrophages,CD4 Tr1,HSPA8,ADRB2,37.831480,0.000,0.000227,0.693847
175097,Follicle Associated Resident Macrophages,CD4 Tr1,ARPC5,ADRB2,34.604070,0.000,0.000437,0.684112
137943,Follicle Associated Resident Macrophages,CD4 Tr1,CD22,PTPRC,103.899030,0.000,0.000079,0.678344
237464,Follicle Associated Resident Macrophages,CD4 Tr1,GNAS,ADRB2,28.574558,0.000,0.000210,0.662603
245096,Follicle Associated Resident Macrophages,CD4 Tr1,IL1B,ADRB2,27.981997,0.000,0.000431,0.660199
1244747,CD4 Tr1,Follicle Associated Resident Macrophages,SEMA4D,PLXNB2,8.560137,0.000,0.000471,0.643080
311189,Follicle Associated Resident Macrophages,CD4 Tr1,ACTR2,ADRB2,23.839954,0.000,0.000329,0.641513
598677,CD4 Tr1,Follicle Associated Resident Macrophages,GNAI2,UNC5B,15.129110,0.000,0.000277,0.638352

=== FARM <-> CD4 pTreg ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
4655,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-B,CD3D,268.41876,0.0,0.001490,0.981852
279,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DRA,LAG3,739.27106,0.0,0.006583,0.975737
14318,Follicle Associated Resident Macrophages,CD4 pTreg,LGALS1,PTPRC,142.53537,0.0,0.000646,0.969850
356,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DRA,CD4,734.75214,0.0,0.002238,0.968418
2271,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DPA1,LAG3,388.85526,0.0,0.007668,0.966634
2320,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DRB1,LAG3,383.99777,0.0,0.006545,0.966425
3111,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DPB1,LAG3,324.14980,0.0,0.006529,0.963471
717,CD4 pTreg,Follicle Associated Resident Macrophages,COPA,CD74,812.68600,0.0,0.000695,0.961204
26608,Follicle Associated Resident Macrophages,CD4 pTreg,LGALS1,CD69,105.68643,0.0,0.000476,0.958998
2316,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DPA1,CD4,384.33633,0.0,0.002607,0.956691
2401,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DRB1,CD4,379.47885,0.0,0.002225,0.956422
3208,Follicle Associated Resident Macrophages,CD4 pTreg,HLA-DPB1,CD4,319.63090,0.0,0.002220,0.952631

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
14318,Follicle Associated Resident Macrophages,CD4 pTreg,LGALS1,PTPRC,142.535370,0.000,0.000646,0.969850
33866,Follicle Associated Resident Macrophages,CD4 pTreg,LGALS9,PTPRC,90.458000,0.000,0.001542,0.933551
37836,Follicle Associated Resident Macrophages,CD4 pTreg,MRC1,PTPRC,84.660805,0.000,0.001742,0.910763
180122,CD4 pTreg,Follicle Associated Resident Macrophages,LGALS1,PTPRC,33.961502,1.000,0.000017,0.840562
256261,Follicle Associated Resident Macrophages,CD4 pTreg,CALM1,PTPRA,27.207825,1.000,0.000097,0.827894
111654,CD4 pTreg,Follicle Associated Resident Macrophages,CALM1,PTPRA,46.114178,0.000,0.000081,0.813987
214517,CD4 pTreg,Follicle Associated Resident Macrophages,LGALS9,PTPRC,30.516014,0.412,0.000055,0.725583
162080,CD4 pTreg,Follicle Associated Resident Macrophages,HSPA8,ADRB2,43.805973,0.000,0.000163,0.657862
176378,Follicle Associated Resident Macrophages,CD4 pTreg,CD22,PTPRC,78.390920,0.000,0.000060,0.646797
1103570,CD4 pTreg,Follicle Associated Resident Macrophages,VEGFB,NRP1,9.425758,0.000,0.000322,0.638054
1219546,Follicle Associated Resident Macrophages,CD4 pTreg,THBS1,PTPRJ,8.704042,0.000,0.000110,0.622698
1339986,CD4 pTreg,Follicle Associated Resident Macrophages,SPTAN1,PTPRA,8.046620,0.000,0.000087,0.616353
803693,CD4 pTreg,Follicle Associated Resident Macrophages,GNAI2,UNC5B,12.035923,0.000,0.000216,0.609187
1614452,CD4 pTreg,Follicle Associated Resident Macrophages,SEMA4D,PLXNB2,6.788250,0.000,0.000329,0.600888
1689700,CD4 pTreg,Follicle Associated Resident Macrophages,SEMA4D,CD72,6.499775,0.000,0.000457,0.587201

=== FARM <-> CD4 tTreg ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
4981,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-B,CD3D,258.113160,0.0,0.001279,0.980440
13352,Follicle Associated Resident Macrophages,CD4 tTreg,LGALS1,PTPRC,148.383530,0.0,0.000694,0.970887
291,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-DRA,CD4,735.793760,0.0,0.002610,0.970683
448,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-DRA,LAG3,734.354700,0.0,0.003585,0.967402
722,CD4 tTreg,Follicle Associated Resident Macrophages,COPA,CD74,812.656070,0.0,0.000689,0.961052
2306,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-DPA1,CD4,385.377930,0.0,0.003040,0.959763
2384,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-DRB1,CD4,380.520450,0.0,0.002595,0.959513
26143,Follicle Associated Resident Macrophages,CD4 tTreg,LGALS1,CD69,106.730125,0.0,0.000488,0.959485
3189,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-DPB1,CD4,320.672500,0.0,0.002588,0.955978
2323,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-DPA1,LAG3,383.938870,0.0,0.004176,0.955315
2407,Follicle Associated Resident Macrophages,CD4 tTreg,HLA-DRB1,LAG3,379.081400,0.0,0.003564,0.955039
36437,Follicle Associated Resident Macrophages,CD4 tTreg,HMGB1,CXCR4,86.559860,0.0,0.000289,0.951181

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
13352,Follicle Associated Resident Macrophages,CD4 tTreg,LGALS1,PTPRC,148.383530,0.000,0.000694,0.970887
30962,Follicle Associated Resident Macrophages,CD4 tTreg,LGALS9,PTPRC,96.306150,0.000,0.001657,0.935754
33836,Follicle Associated Resident Macrophages,CD4 tTreg,MRC1,PTPRC,90.508960,0.000,0.001872,0.913652
249089,Follicle Associated Resident Macrophages,CD4 tTreg,CALM1,PTPRA,27.697048,1.000,0.000107,0.834339
150626,CD4 tTreg,Follicle Associated Resident Macrophages,CALM1,PTPRA,38.003740,1.000,0.000066,0.798066
203268,CD4 tTreg,Follicle Associated Resident Macrophages,LGALS1,PTPRC,31.519537,1.000,0.000008,0.783198
217228,CD4 tTreg,Follicle Associated Resident Macrophages,LGALS9,PTPRC,30.239573,0.484,0.000042,0.697608
165045,Follicle Associated Resident Macrophages,CD4 tTreg,CD22,PTPRC,84.239075,0.000,0.000064,0.654992
1265955,CD4 tTreg,Follicle Associated Resident Macrophages,SEMA4D,PLXNB2,8.445692,0.000,0.000462,0.640818
1318928,CD4 tTreg,Follicle Associated Resident Macrophages,SEMA4D,CD72,8.157217,0.000,0.000642,0.627652
1241017,Follicle Associated Resident Macrophages,CD4 tTreg,THBS1,PTPRJ,8.580837,0.000,0.000108,0.620528
1154477,CD4 tTreg,Follicle Associated Resident Macrophages,VEGFB,NRP1,9.106823,0.000,0.000272,0.618289
225317,CD4 tTreg,Follicle Associated Resident Macrophages,HSPA8,ADRB2,30.100534,0.000,0.000112,0.613960
1393555,CD4 tTreg,Follicle Associated Resident Macrophages,SPTAN1,PTPRA,7.785996,0.000,0.000083,0.611026
1012805,CD4 tTreg,Follicle Associated Resident Macrophages,GNAI2,UNC5B,10.056294,0.000,0.000177,0.585227

=== FARM <-> Gamma Delta T Cells ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
385,Follicle Associated Resident Macrophages,Gamma Delta T Cells,B2M,KLRD1,690.428800,0.0,0.001940,0.982270
5336,Follicle Associated Resident Macrophages,Gamma Delta T Cells,HLA-B,CD3D,244.591050,0.0,0.001002,0.977957
421,Follicle Associated Resident Macrophages,Gamma Delta T Cells,B2M,KLRC1,680.120060,0.0,0.001980,0.975995
428,Follicle Associated Resident Macrophages,Gamma Delta T Cells,B2M,KLRC2,677.808600,0.0,0.001926,0.973364
6646,Follicle Associated Resident Macrophages,Gamma Delta T Cells,HLA-B,KLRD1,218.020780,0.0,0.002041,0.967725
6956,Follicle Associated Resident Macrophages,Gamma Delta T Cells,HLA-B,CD8B,214.043670,0.0,0.002187,0.964519
18365,Follicle Associated Resident Macrophages,Gamma Delta T Cells,HMGB1,CXCR4,125.942320,0.0,0.000523,0.963272
22528,Follicle Associated Resident Macrophages,Gamma Delta T Cells,LGALS1,PTPRC,116.021850,0.0,0.000427,0.963168
22981,Follicle Associated Resident Macrophages,Gamma Delta T Cells,LGALS1,CD69,114.875206,0.0,0.000582,0.962767
7089,Follicle Associated Resident Macrophages,Gamma Delta T Cells,HLA-B,CD8A,210.968830,0.0,0.001500,0.961246
870,Gamma Delta T Cells,Follicle Associated Resident Macrophages,COPA,CD74,812.093600,0.0,0.000583,0.957806
901,Follicle Associated Resident Macrophages,Gamma Delta T Cells,HLA-DRA,LAG3,731.740540,0.0,0.001991,0.956738

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
22528,Follicle Associated Resident Macrophages,Gamma Delta T Cells,LGALS1,PTPRC,116.021850,0.000,0.000427,0.963168
62543,Follicle Associated Resident Macrophages,Gamma Delta T Cells,LGALS9,PTPRC,63.944470,0.000,0.001019,0.919492
74811,Follicle Associated Resident Macrophages,Gamma Delta T Cells,MRC1,PTPRC,58.147274,0.000,0.001151,0.892439
173384,Gamma Delta T Cells,Follicle Associated Resident Macrophages,LGALS1,PTPRC,34.855920,1.000,0.000021,0.852103
268206,Follicle Associated Resident Macrophages,Gamma Delta T Cells,CALM1,PTPRA,26.337925,1.000,0.000081,0.814118
181397,Gamma Delta T Cells,Follicle Associated Resident Macrophages,CALM1,PTPRA,33.799366,1.000,0.000058,0.787839
208647,Gamma Delta T Cells,Follicle Associated Resident Macrophages,LGALS9,PTPRC,31.043173,0.284,0.000079,0.761318
1233251,Gamma Delta T Cells,Follicle Associated Resident Macrophages,SEMA4D,PLXNB2,8.622633,0.000,0.000476,0.644294
1285002,Gamma Delta T Cells,Follicle Associated Resident Macrophages,SEMA4D,CD72,8.334158,0.000,0.000661,0.631183
245613,Gamma Delta T Cells,Follicle Associated Resident Macrophages,HSPA8,ADRB2,27.941044,0.039,0.000104,0.604972
249387,Follicle Associated Resident Macrophages,Gamma Delta T Cells,CD22,PTPRC,51.877396,0.000,0.000040,0.598182
251748,Follicle Associated Resident Macrophages,Gamma Delta T Cells,HSPA8,ADRB2,37.444927,0.000,0.000096,0.596322
270928,Follicle Associated Resident Macrophages,Gamma Delta T Cells,ARPC5,ADRB2,34.217518,0.000,0.000185,0.585340
1183106,Gamma Delta T Cells,Follicle Associated Resident Macrophages,GNAI2,UNC5B,8.930197,0.000,0.000155,0.568874
1256685,Gamma Delta T Cells,Follicle Associated Resident Macrophages,VEGFB,NRP1,8.495535,0.000,0.000176,0.565668

=== FARM <-> NKT Cells ===  n=8978

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
415,Follicle Associated Resident Macrophages,NKT Cells,B2M,KLRD1,683.21560,0.0,0.001314,0.978536
420,Follicle Associated Resident Macrophages,NKT Cells,B2M,KLRC2,680.44190,0.0,0.002448,0.976302
436,Follicle Associated Resident Macrophages,NKT Cells,B2M,KLRC1,676.82623,0.0,0.001438,0.971948
6519,Follicle Associated Resident Macrophages,NKT Cells,HLA-B,CD3D,220.36725,0.0,0.000506,0.969249
19699,Follicle Associated Resident Macrophages,NKT Cells,LGALS1,PTPRC,122.41185,0.0,0.000480,0.965181
638,Follicle Associated Resident Macrophages,NKT Cells,HLA-DRA,LAG3,732.79630,0.0,0.002634,0.962180
7096,Follicle Associated Resident Macrophages,NKT Cells,HLA-B,KLRD1,210.80762,0.0,0.001382,0.961048
878,NKT Cells,Follicle Associated Resident Macrophages,COPA,CD74,812.05940,0.0,0.000577,0.957581
28893,Follicle Associated Resident Macrophages,NKT Cells,LGALS1,CD69,101.13844,0.0,0.000424,0.956643
2343,Follicle Associated Resident Macrophages,NKT Cells,HLA-DPA1,LAG3,382.38050,0.0,0.003069,0.948260
2441,Follicle Associated Resident Macrophages,NKT Cells,HLA-DRB1,LAG3,377.52300,0.0,0.002619,0.947942
3270,Follicle Associated Resident Macrophages,NKT Cells,HLA-DPB1,LAG3,317.67505,0.0,0.002613,0.943457

  neuro/axon hits:

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,spec_weight,lrscore
19699,Follicle Associated Resident Macrophages,NKT Cells,LGALS1,PTPRC,122.411850,0.000,0.000480,0.965181
52526,Follicle Associated Resident Macrophages,NKT Cells,LGALS9,PTPRC,70.334470,0.000,0.001145,0.923704
108434,NKT Cells,Follicle Associated Resident Macrophages,LGALS1,PTPRC,47.053593,0.000,0.000067,0.911788
61395,Follicle Associated Resident Macrophages,NKT Cells,MRC1,PTPRC,64.537280,0.000,0.001294,0.897908
236631,Follicle Associated Resident Macrophages,NKT Cells,CALM1,PTPRA,28.625032,1.000,0.000124,0.844707
100065,NKT Cells,Follicle Associated Resident Macrophages,CALM1,PTPRA,49.421658,0.000,0.000087,0.819412
507436,Follicle Associated Resident Macrophages,NKT Cells,RTN4,LINGO1,17.034143,0.000,0.001094,0.774813
208785,NKT Cells,Follicle Associated Resident Macrophages,LGALS9,PTPRC,31.025623,0.292,0.000079,0.760366
849053,NKT Cells,Follicle Associated Resident Macrophages,VEGFB,NRP1,11.539065,0.000,0.000654,0.715325
581840,NKT Cells,Follicle Associated Resident Macrophages,GNAI2,UNC5B,15.430880,0.000,0.000283,0.640801
1316668,NKT Cells,Follicle Associated Resident Macrophages,SEMA4D,PLXNB2,8.167604,0.000,0.000440,0.635101
1373712,NKT Cells,Follicle Associated Resident Macrophages,SEMA4D,CD72,7.879129,0.000,0.000611,0.621850
215724,NKT Cells,Follicle Associated Resident Macrophages,GNAS,ADRB2,31.653315,0.000,0.000145,0.619984
228105,Follicle Associated Resident Macrophages,NKT Cells,CD22,PTPRC,58.267400,0.000,0.000044,0.612111
232708,NKT Cells,Follicle Associated Resident Macrophages,HSPA8,ADRB2,28.969809,0.000,0.000107,0.609348

## 3. Figures (Nature-style PDF)
Bar panels: top interactions by `lrscore` per question group. **All figure text in black**; bars use the Nature/Wong palette; **Helvetica** (fallback Arial / DejaVu). **Direction**: LIANA uses **source** and **target**; **ligand** is on **source** cells, **receptor** on **target** cells. Row labels list **ligand — receptor** (not an arrow). Where tables pool **bidirectional** masks, each plotted value is the **max** `lrscore` over **both** orientations (e.g. Glia→epithelium and epithelium→Glia). Notes are printed on the PDFs (footer or second line of title).

In [7]:
# --- Fig 1: Epithelium / progenitors ↔ Glia (10 panels, a–j) ---
glia_items = list(glia_tables.items())
nrows, ncols = 5, 2
fig1, axes1 = plt.subplots(nrows, ncols, figsize=(7.2, 11.0), constrained_layout=True)
axes1 = axes1.ravel()
letters = "abcdefghijklmnopqrst"
for i, (name, sub) in enumerate(glia_items):
    ax = axes1[i]
    panel_label(ax, letters[i] + ")")
    hbar_top_lr(sub, ax, title=name.replace(" <-> ", " ↔ "), n=10)
for j in range(len(glia_items), len(axes1)):
    axes1[j].set_axis_off()
fig1.suptitle(
    "Ileum LIANA: epithelial / progenitor <-> Glia (top lrscore)\n" + LIANA_NOTE_GLIA_BARS,
    fontsize=7,
    color=NATURE_WONG["black"],
    y=1.03,
)
save_pdf(fig1, FIG_DIR / "fig1_epithelium_glia_lrscore.pdf")

# --- Fig 2: FARM ↔ lymphocyte subsets (8 panels) ---
farm_items = sorted(farm_tables.items(), key=lambda x: x[0])
fig2, axes2 = plt.subplots(4, 2, figsize=(7.2, 9.2), constrained_layout=True)
axes2 = axes2.ravel()
for i, (tname, sub) in enumerate(farm_items):
    ax = axes2[i]
    panel_label(ax, letters[i] + ")")
    short = tname.replace("CD4 ", "").replace("Gamma Delta T Cells", "γδ T").replace("Cells", "").strip()
    hbar_top_lr(sub, ax, title=f"FARM ↔ {short}", n=10)
for j in range(len(farm_items), len(axes2)):
    axes2[j].set_axis_off()
fig2.suptitle(
    "Ileum LIANA: Follicle-associated resident macrophages <-> T / NK (top lrscore)\n" + LIANA_NOTE_FARM_BARS,
    fontsize=7,
    color=NATURE_WONG["black"],
    y=1.03,
)
save_pdf(fig2, FIG_DIR / "fig2_farm_lymphocyte_lrscore.pdf")

print("Figure directory:", FIG_DIR.resolve())

/var/folders/zc/5fly3ly908xb0pd8zy6m6bj80000gn/T/ipykernel_96935/3147547659.py:59: UserWarning: Glyph 8596 (\N{LEFT RIGHT ARROW}) missing from font(s) Helvetica.
  fig.savefig(
1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp
/var/folders/zc/5fly3ly908xb0pd8zy6m6bj80000gn/T/ipykernel_96935/3147547659.py:59: UserWarning: Glyph 8596 (\N{LEFT RIGHT ARROW}) missing from font(s) Helvetica.
  fig.savefig(

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig1_epithelium_glia_lrscore.pdf

1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig2_farm_lymphocyte_lrscore.pdf
Figure directory: /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures

In [8]:
# --- Fig 3: Neurotransmitter / axon keyword hits (epithelium–Glia, pooled) ---
na_parts = []
for gname, sub in glia_tables.items():
    hit = sub[neuro_axon_mask(sub)]
    if len(hit):
        h = hit.copy()
        h["group"] = gname
        na_parts.append(h)
if na_parts:
    na_all = pd.concat(na_parts, ignore_index=True)
    na_all = na_all.sort_values("lrscore", ascending=False)
    na_dedup = na_all.drop_duplicates(subset=["ligand_complex", "receptor_complex"]).head(22)
else:
    na_dedup = pd.DataFrame(columns=USECOLS + ["group"])

fig3, ax3 = plt.subplots(figsize=(3.5, 6.5))
panel_label(ax3, "a)")
hbar_top_lr(na_dedup, ax3, title="Neuro / axon keyword hits (any epithelium–Glia group)", n=min(22, len(na_dedup)))
fig3.suptitle(
    "Ileum LIANA: neurotransmitter & axon-guidance keywords\n" + LIANA_NOTE_GLIA_BARS,
    fontsize=7,
    color=NATURE_WONG["black"],
    y=1.03,
)
save_pdf(fig3, FIG_DIR / "fig3_neuro_axon_epithelium_glia.pdf")

1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig3_neuro_axon_epithelium_glia.pdf

### Differential CCC (epithelium ↔ Glia)
Heatmaps: **columns** = epithelial subset context (Fig. 1 groups, including **BEST4 colonocytes** separately from **BEST4 enterocytes**, and **Lower Villus enterocytes** as a **control** column). **Row ranking** uses variability **excluding** the **Villus bottom** column so control-driven pairs are not promoted. **PYY / SST / NTS / TPH1** outgoing interactions are collapsed to **one canonical L–R per hormone** before plotting. Two PDFs: **all** pairs vs **neuro / axon keyword** hits only. **Scatter / delta** (below) use **neuro / axon** colouring between two epithelial contexts.

In [9]:
# Short x-axis labels (epithelial subset context); Glia appears in figure titles only.
EPI_CONTEXT_LABELS = {
    "EEC L <-> Glia": "EEC L",
    "EEC I (CCK+) <-> Glia": "EEC I (CCK+)",
    "EEC (mature) <-> Glia": "EEC (mature)",
    "BEST4 Enterocyte <-> Glia": "BEST4 enterocyte",
    "BEST4 Colonocytes <-> Glia": "BEST4 colonocyte",
    "Tuft <-> Glia": "Tuft",
    "EEC Progenitors <-> Glia": "EEC prog.",
    "Tuft Progenitors <-> Glia": "Tuft prog.",
    "Secretory Progenitors <-> Glia": "Secr. prog.",
    "Villus-bottom enterocytes <-> Glia": "Villus bottom",
}
# Heatmap row ranking excludes this column (control epithelium; not used to pick top variable pairs)
GLIA_HEATMAP_CTRL_COL = "Villus bottom"


def wide_epithelium_glia(glia_tables: dict, neuro_only: bool) -> pd.DataFrame:
    parts = []
    for gname, sub in glia_tables.items():
        s = sub
        if neuro_only:
            s = s[neuro_axon_mask(s)]
        if s.empty:
            continue
        m = max_lr_per_pair(s)
        col = EPI_CONTEXT_LABELS.get(gname, shorten_label(gname, 18))
        parts.append(m.set_index(["ligand_complex", "receptor_complex"])["lrscore"].rename(col))
    if not parts:
        return pd.DataFrame()
    return pd.concat(parts, axis=1)


def plot_glia_epithelium_diff_heatmap(
    wide: pd.DataFrame,
    *,
    axis_title: str,
    suptitle: str,
    outfile: Path,
    top_n: int = 40,
    exclude_cols_for_ranking: set[str] | None = None,
    rank_by_column: str | None = None,
    direction_note: str | None = None,
) -> None:
    if wide.empty or wide.shape[1] < 1:
        print("Skipping heatmap (no data):", outfile.name)
        return
    if rank_by_column is not None and rank_by_column in wide.columns:
        ranked = wide[rank_by_column].dropna().sort_values(ascending=False)
        if ranked.empty:
            print("Skipping heatmap (no non-null values in rank column):", rank_by_column, outfile.name)
            return
        n = min(top_n, len(ranked))
        heat = wide.loc[ranked.head(n).index]
    else:
        exc = exclude_cols_for_ranking or set()
        cols_rank = [c for c in wide.columns if c not in exc]
        if not cols_rank:
            cols_rank = list(wide.columns)
        wide_rank = wide[cols_rank]
        rank_var = wide_rank.std(axis=1, skipna=True).dropna().sort_values(ascending=False)
        if rank_var.empty:
            rank_var = wide_rank.max(axis=1, skipna=True).sort_values(ascending=False)
        n = min(top_n, len(rank_var))
        heat = wide.loc[rank_var.head(n).index]
    note = direction_note if direction_note is not None else LIANA_NOTE_GLIA_HEATMAP
    fig_h, ax_h = plt.subplots(figsize=(7.2, 8.8))
    fig_h.subplots_adjust(bottom=0.2, top=0.86)
    panel_label(ax_h, "a)")
    data = np.ma.masked_invalid(heat.values.astype(float))
    vmin_h = float(np.nanmin(heat.values))
    vmax_h = float(np.nanmax(heat.values))
    if vmin_h == vmax_h:
        vmax_h = vmin_h + 1e-9
    im = ax_h.imshow(data, aspect="auto", cmap=NATURE_CMAP, vmin=vmin_h, vmax=vmax_h)
    ax_h.set_yticks(np.arange(len(heat)))
    ax_h.set_yticklabels(
        [shorten_label(f"{a} — {b}") for a, b in heat.index],
        fontsize=5,
        color=NATURE_WONG["black"],
    )
    ax_h.set_xticks(np.arange(heat.shape[1]))
    ax_h.set_xticklabels(list(heat.columns), rotation=45, ha="right", fontsize=6, color=NATURE_WONG["black"])
    ax_h.set_xlabel("Epithelial subset (vs Glia)", color=NATURE_WONG["black"], fontsize=7)
    ax_h.set_title(axis_title, fontsize=7, color=NATURE_WONG["black"])
    cbar = fig_h.colorbar(im, ax=ax_h, fraction=0.035, pad=0.02)
    cbar.ax.tick_params(colors=NATURE_WONG["black"])
    cbar.set_label("lrscore (unitless)", color=NATURE_WONG["black"], fontsize=6)
    for t in cbar.ax.get_yticklabels():
        t.set_color(NATURE_WONG["black"])
    fig_h.suptitle(suptitle, fontsize=7, color=NATURE_WONG["black"], y=0.98)
    fig_h.text(
        0.5,
        0.06,
        note,
        ha="center",
        va="top",
        fontsize=5.5,
        color=NATURE_WONG["black"],
        transform=fig_h.transFigure,
    )
    save_pdf(fig_h, outfile)


wide_all = wide_epithelium_glia(glia_tables, neuro_only=False)
plot_glia_epithelium_diff_heatmap(
    wide_all,
    axis_title="Glia: variable L–R pairs across epithelial contexts (max lrscore, all pairs)",
    suptitle="Differential CCC (ileum LIANA): Glia vs epithelial subsets",
    outfile=FIG_DIR / "fig_epithelium_glia_diff_heatmap_all.pdf",
    exclude_cols_for_ranking={GLIA_HEATMAP_CTRL_COL},
)

wide_na = wide_epithelium_glia(glia_tables, neuro_only=True)
plot_glia_epithelium_diff_heatmap(
    wide_na,
    axis_title="Glia: variable L–R pairs (neuro / axon keywords only)",
    suptitle="Differential CCC (ileum LIANA): Glia vs epithelial subsets (neuro / axon)",
    outfile=FIG_DIR / "fig_epithelium_glia_diff_heatmap_neuro_axon.pdf",
    exclude_cols_for_ranking={GLIA_HEATMAP_CTRL_COL},
)

# --- Glia / epithelium: scatter & delta (neuro / axon stratification) ---
SC_A, SC_B = "EEC (mature)", "Tuft"
sc_cols = [c for c in (SC_A, SC_B) if c in wide_all.columns]
if len(sc_cols) < 2:
    sc_cols = list(wide_all.columns)[:2]
if len(sc_cols) >= 2:
    ca, cb = sc_cols[0], sc_cols[1]
    scat = wide_all[[ca, cb]].dropna(how="any").reset_index()
    scat["neuro_axon"] = neuro_axon_mask(scat)
    fig_es, ax_es = plt.subplots(figsize=(3.5, 3.5))
    panel_label(ax_es, "a)")
    oth = ~scat["neuro_axon"]
    ax_es.scatter(
        scat.loc[oth, ca],
        scat.loc[oth, cb],
        s=10,
        c=NATURE_WONG["sky_blue"],
        edgecolors=NATURE_WONG["black"],
        linewidths=0.35,
        alpha=0.55,
        label="Other L–R",
    )
    ax_es.scatter(
        scat.loc[scat["neuro_axon"], ca],
        scat.loc[scat["neuro_axon"], cb],
        s=14,
        c=NATURE_WONG["vermillion"],
        edgecolors=NATURE_WONG["black"],
        linewidths=0.35,
        alpha=0.9,
        label="Neuro / axon keyword",
    )
    mx = float(max(scat[ca].max(), scat[cb].max()))
    ax_es.plot([0, mx], [0, mx], color=NATURE_WONG["black"], linewidth=0.6, linestyle="--", alpha=0.65)
    ax_es.set_xlabel(f"lrscore Glia <-> {ca} (unitless)", color=NATURE_WONG["black"])
    ax_es.set_ylabel(f"lrscore Glia <-> {cb} (unitless)", color=NATURE_WONG["black"])
    ax_es.set_title(f"Matched pairs: {ca} vs {cb}", fontsize=7, color=NATURE_WONG["black"])
    leg_es = ax_es.legend(frameon=False, loc="upper left", fontsize=6, handlelength=1.2)
    for tx in leg_es.get_texts():
        tx.set_color(NATURE_WONG["black"])
    ax_es.tick_params(colors=NATURE_WONG["black"])
    fig_es.subplots_adjust(bottom=0.2)
    fig_es.suptitle(
        "Differential CCC (Glia): epithelial contexts (neuro / axon)",
        fontsize=7,
        color=NATURE_WONG["black"],
        y=1.06,
    )
    fig_es.text(
        0.5,
        0.03,
        LIANA_NOTE_SHORT,
        ha="center",
        va="bottom",
        fontsize=5,
        color=NATURE_WONG["black"],
        transform=fig_es.transFigure,
    )
    save_pdf(fig_es, FIG_DIR / "fig_epithelium_glia_diff_scatter_neuro_axon.pdf")

    scat["delta"] = scat[ca] - scat[cb]
    top_ed = scat.reindex(scat["delta"].abs().sort_values(ascending=False).index).head(18)
    fig_ed, ax_ed = plt.subplots(figsize=(3.5, 5.5))
    panel_label(ax_ed, "b)")
    ye = np.arange(len(top_ed))
    bar_c = [
        NATURE_WONG["vermillion"] if neuro_axon_mask(top_ed.iloc[[i]]).iloc[0] else NATURE_WONG["sky_blue"]
        for i in range(len(top_ed))
    ]
    ax_ed.barh(ye, top_ed["delta"], color=bar_c, edgecolor=NATURE_WONG["black"], linewidth=0.35)
    labs_ed = [
        shorten_label(f"{a} — {b}") for a, b in zip(top_ed["ligand_complex"], top_ed["receptor_complex"])
    ]
    ax_ed.set_yticks(ye)
    ax_ed.set_yticklabels(labs_ed, fontsize=5.5, color=NATURE_WONG["black"])
    ax_ed.invert_yaxis()
    ax_ed.set_xlabel(f"Δ lrscore ({ca} − {cb}) (unitless)", color=NATURE_WONG["black"])
    ax_ed.set_title("Largest |Δ| (Glia-linked)", fontsize=7, color=NATURE_WONG["black"])
    ax_ed.axvline(0, color=NATURE_WONG["black"], linewidth=0.5)
    ax_ed.tick_params(colors=NATURE_WONG["black"])
    ax_ed.spines["top"].set_visible(False)
    ax_ed.spines["right"].set_visible(False)
    leg_ed = ax_ed.legend(
        handles=[
            Patch(facecolor=NATURE_WONG["vermillion"], edgecolor=NATURE_WONG["black"], label="Neuro / axon keyword"),
            Patch(facecolor=NATURE_WONG["sky_blue"], edgecolor=NATURE_WONG["black"], label="Other"),
        ],
        frameon=False,
        loc="lower right",
        fontsize=6,
    )
    for tx in leg_ed.get_texts():
        tx.set_color(NATURE_WONG["black"])
    fig_ed.subplots_adjust(bottom=0.18)
    fig_ed.suptitle(
        "Differential CCC (Glia): epithelial contrast (neuro / axon)",
        fontsize=7,
        color=NATURE_WONG["black"],
        y=1.02,
    )
    fig_ed.text(
        0.5,
        0.02,
        LIANA_NOTE_SHORT,
        ha="center",
        va="bottom",
        fontsize=5,
        color=NATURE_WONG["black"],
        transform=fig_ed.transFigure,
    )
    save_pdf(fig_ed, FIG_DIR / "fig_epithelium_glia_diff_delta_neuro_axon.pdf")
else:
    print("Skipping epithelial scatter/delta: need ≥2 columns in wide_all")

1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_diff_heatmap_all.pdf

1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp
1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp
1 extra bytes in post.stringData array
'created' timestamp seems very low; regarding as unix timestamp

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_diff_heatmap_neuro_axon.pdf
Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_diff_scatter_neuro_axon.pdf
Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_diff_delta_neuro_axon.pdf

### Epithelium–Glia: BEST4 CFTR split & villus columns (de novo LIANA)
The ileum LIANA CSV does not separate **BEST4 Enterocytes** by **CFTR** expression. This block loads a **memory subset** of the integrated atlas (ileum cells), assigns **CFTR-high** vs **not-high** among BEST4 enterocytes (median **log1p CFTR**), runs **`liana`** on small **Glia + epithelium** subsets, and merges results with **`wide_all`** from the precomputed table.
**`rank_aggregate` output** lists **all** sender–receiver pairs among the `groupby` labels, including **within-group** rows where **`source == target`** (e.g. BEST4_Ent_CFTRhi → BEST4_Ent_CFTRhi). Those are **not** used for the Glia heatmap columns: **`_lr_series_from_liana`** keeps only **Glia ↔ epithelial** pairs (**no** autocrine / within-epithelium-only).
- **Heatmaps (all pairs + neuro/axon, CFTR split)**: same matrices as `fig_epithelium_glia_diff_heatmap_all.pdf` and `fig_epithelium_glia_diff_heatmap_neuro_axon.pdf`, but **BEST4 enterocyte** is replaced by **BEST4 CFTR-hi** and **BEST4 CFTR-lo** → `fig_epithelium_glia_diff_heatmap_all_cftr_split.pdf`, `fig_epithelium_glia_diff_heatmap_neuro_axon_cftr_split.pdf`.
- **Heatmap (CFTR focus)**: same epithelial contexts as §differential heatmaps, but **BEST4 enterocyte** is replaced by **BEST4 CFTR-hi** and **BEST4 CFTR-lo**; **rows ranked by lrscore in the CFTR-hi column** (Glia ↔ CFTR-high BEST4).
- **Heatmap (curated gene panel)**: same **`wide_cftr`** matrix, but **only L–R pairs** whose `ligand_complex` / `receptor_complex` strings hit **human (HGNC)** symbols including: epithelial/ion (**BEST4, CFTR, OTOP2, CA7, GUCA2A/B, GUCY2C**); presynaptic (**SYN1, PCLO, BSN, UNC13B, RIMS2, SYT3, NOTCH2**); postsynaptic/scaffold (**HOMER3, DLG4**); **NRXN/NLGN**; **EFNB/EPH**; **LRRTM**, **LRRC4**; IgCAM-type (**NCAM1, L1CAM, CADM1–3, PTPRF, DSCAM, OPCML**); glutamate vesicular transporters (**SLC17A7, SLC17A6**); neurotrophin/RET (**NTRK1, GFRA1–4, RET, NGF, ARTN, GDNF, NRTN**); axon guidance (**SEMA, PLXN, NRP, NTN, DCC, UNC5, SLIT, ROBO** families as listed in the notebook). Ranked by **CFTR-hi** when available → `fig_epithelium_glia_neuropod_epithelial_gene_panel.pdf`.
- **Heatmap (villus column)**: **Glia** vs **BEST4 colonocytes**, **Lower villus enterocytes**, **Villus tip enterocytes** only (de novo LIANA on those four types).
Requires `pip install liana` and sufficient cells per group (≥ ~5 per identity).

In [10]:
try:
    import liana as li
except ImportError as exc:
    raise ImportError("Install liana: pip install liana") from exc

COL_BEST4_ENT = EPI_CONTEXT_LABELS["BEST4 Enterocyte <-> Glia"]  # "BEST4 enterocyte"
FOCUS_CFTR_COL = "BEST4 CFTR-hi"


def _glia_epi_block(df: pd.DataFrame, epithelial: str) -> pd.DataFrame:
    """Rows where Glia <-> epithelial (bidirectional). Excludes within-group / autocrine (source==target==epi)."""
    if df is None or df.empty:
        return pd.DataFrame()
    s = df["source"].astype(str)
    t = df["target"].astype(str)
    epi = str(epithelial)
    m = ((s == epi) & (t == "Glia")) | ((s == "Glia") & (t == epi))
    return df.loc[m].copy()


def _fill_ligand_receptor_complex_from_simple(sub: pd.DataFrame) -> pd.DataFrame:
    """LIANA often has ligand/receptor; ligand_complex may be empty — fill for indexing."""
    if sub.empty:
        return sub
    out = sub.copy()
    if "ligand_complex" in out.columns and "ligand" in out.columns:
        lc = out["ligand_complex"]
        m = lc.isna() | (lc.astype(str).str.strip().eq("")) | (lc.astype(str).str.lower().eq("nan"))
        out.loc[m, "ligand_complex"] = out.loc[m, "ligand"].astype(str)
    if "receptor_complex" in out.columns and "receptor" in out.columns:
        rc = out["receptor_complex"]
        m = rc.isna() | (rc.astype(str).str.strip().eq("")) | (rc.astype(str).str.lower().eq("nan"))
        out.loc[m, "receptor_complex"] = out.loc[m, "receptor"].astype(str)
    return out


def _lr_series_from_liana(df: pd.DataFrame, epithelial: str, col_name: str) -> pd.Series:
    """Max lrscore per L-R for Glia <-> epithelial only (ignores rank_aggregate within-group rows)."""
    sub = _glia_epi_block(df, epithelial)
    if sub.empty:
        return pd.Series(dtype=float, name=col_name)
    if "lrscore" not in sub.columns:
        for alt in ("aggregate_rank", "lr_mean", "mean_rank"):
            if alt in sub.columns:
                sub = sub.rename(columns={alt: "lrscore"})
                break
    if "lrscore" not in sub.columns:
        return pd.Series(dtype=float, name=col_name)
    sub = _fill_ligand_receptor_complex_from_simple(sub)
    sub = reduce_canonical_neuropeptide_outgoing(sub)
    m = max_lr_per_pair(sub)
    return m.set_index(["ligand_complex", "receptor_complex"])["lrscore"].rename(col_name)


TISSUE_COL = "tissue_ontology_term"
ad_back = sc.read_h5ad(INTEGRATED, backed="r")
obs = ad_back.obs
mask_ile = obs[TISSUE_COL].astype(str).str.lower().str.contains("ileum", na=False)
types_cftr = {"Glia", "BEST4 Enterocytes"}
mask_ct = obs["hgca_celltype_v1"].astype(str).isin(types_cftr)
ix = np.where((mask_ile & mask_ct).values)[0]
print("Ileum Glia+BEST4 cells for CFTR split:", len(ix))
ad_cf = ad_back[ix].to_memory()
if hasattr(ad_back, "file") and ad_back.file is not None:
    ad_back.file.close()

if "gene_symbol" in ad_cf.var.columns:
    ad_cf.var_names = ad_cf.var["gene_symbol"].astype(str).values
    ad_cf.var_names_make_unique()
if "CFTR" not in ad_cf.var_names:
    raise KeyError("CFTR not in var_names — check gene_symbol mapping")
print(
    "ad_cf var_names use gene symbols (post-mapping): n_var =",
    ad_cf.n_vars,
    "; CFTR present:",
    bool(np.any(ad_cf.var_names.astype(str).str.upper().values == "CFTR")),
)

xcf = ad_cf[:, "CFTR"].X
xcf = xcf.toarray().ravel() if hasattr(xcf, "toarray") else np.asarray(xcf).ravel()
xcf = np.log1p(np.maximum(xcf.astype(float), 0.0))
b4 = ad_cf.obs["hgca_celltype_v1"].astype(str).values == "BEST4 Enterocytes"
thr = float(np.median(xcf[b4])) if b4.sum() else 0.0
cf_hi = np.zeros(ad_cf.n_obs, dtype=bool)
cf_hi[b4] = xcf[b4] >= thr
ad_cf.obs["ccc_group"] = ad_cf.obs["hgca_celltype_v1"].astype(str)
ad_cf.obs.loc[b4 & cf_hi, "ccc_group"] = "BEST4_Ent_CFTRhi"
ad_cf.obs.loc[b4 & ~cf_hi, "ccc_group"] = "BEST4_Ent_CFTRlo"
print("BEST4 ileum: CFTR-hi", int(cf_hi[b4].sum()), "CFTR-lo", int((b4 & ~cf_hi).sum()), "median log1p thr", round(thr, 4))

df_hi = pd.DataFrame()
df_lo = pd.DataFrame()
for lab, tag in [("BEST4_Ent_CFTRhi", "hi"), ("BEST4_Ent_CFTRlo", "lo")]:
    mkeep = ad_cf.obs["ccc_group"].astype(str).isin(["Glia", lab])
    sub = ad_cf[mkeep].copy()
    vc = sub.obs["ccc_group"].value_counts()
    print(f"LIANA subset {tag}:", vc.to_dict())
    if vc.min() < 5:
        print(f"  skip {tag}: <5 cells in a group")
        continue
    try:
        out = li.mt.rank_aggregate(
            sub,
            groupby="ccc_group",
            resource_name="consensus",
            expr_prop=0.1,
            use_raw=False,
            inplace=False,
            verbose=False,
        )
        if isinstance(out, tuple):
            out = out[0]
        dfo = out if isinstance(out, pd.DataFrame) else pd.DataFrame()
        if tag == "hi":
            df_hi = dfo
        else:
            df_lo = dfo
    except Exception as e:
        print(f"LIANA CFTR {tag} failed:", e)

print(
    "Note: rank_aggregate includes within-group (source==target) rows in df_hi/df_lo; "
    "heatmap Glia columns use only Glia↔epithelial pairs (_glia_epi_block), not autocrine."
)

for _lab, _df in (("df_hi", df_hi), ("df_lo", df_lo)):
    if _df is not None and len(_df):
        print(f"--- {_lab}: shape={_df.shape}")
        print("  columns:", list(_df.columns[:min(25, len(_df.columns))]), "..." if len(_df.columns) > 25 else "")
        _need = {"ligand_complex", "receptor_complex", "source", "target"}
        print("  has", _need, "?", {c: c in _df.columns for c in _need})
        if "ligand" in _df.columns and "ligand_complex" in _df.columns:
            _n = _df["ligand_complex"].isna() | (_df["ligand_complex"].astype(str).str.strip().eq(""))
            print("  ligand_complex empty/NaN rows:", int(_n.sum()), "of", len(_df))
        _blk = _glia_epi_block(_df, "BEST4_Ent_CFTRhi" if _lab == "df_hi" else "BEST4_Ent_CFTRlo")
        if len(_blk):
            print("  sample Glia↔epi row (ligand_complex, receptor_complex):", _blk.iloc[0][["ligand_complex", "receptor_complex"]].to_dict())

s_hi = _lr_series_from_liana(df_hi, "BEST4_Ent_CFTRhi", FOCUS_CFTR_COL)
s_lo = _lr_series_from_liana(df_lo, "BEST4_Ent_CFTRlo", "BEST4 CFTR-lo")

wide_cftr = wide_all.drop(columns=[COL_BEST4_ENT], errors="ignore").copy()
wide_cftr = wide_cftr.join(s_hi, how="outer")
wide_cftr = wide_cftr.join(s_lo, how="outer")

# Same as differential heatmaps (all pairs / neuro-axon) but with BEST4 CFTR-hi/lo columns
wide_all_cftr = wide_all.drop(columns=[COL_BEST4_ENT], errors="ignore").copy()
wide_all_cftr = wide_all_cftr.join(s_hi, how="outer").join(s_lo, how="outer")
plot_glia_epithelium_diff_heatmap(
    wide_all_cftr,
    axis_title="Glia: variable L–R pairs (BEST4 CFTR-hi/lo + other subsets; max lrscore, all pairs)",
    suptitle="Differential CCC (ileum LIANA): Glia vs epithelial subsets (BEST4 CFTR-high / CFTR-low)",
    outfile=FIG_DIR / "fig_epithelium_glia_diff_heatmap_all_cftr_split.pdf",
    exclude_cols_for_ranking={GLIA_HEATMAP_CTRL_COL},
)
wide_na_cftr = wide_na.drop(columns=[COL_BEST4_ENT], errors="ignore").copy()
wide_na_cftr = wide_na_cftr.join(s_hi, how="outer").join(s_lo, how="outer")
plot_glia_epithelium_diff_heatmap(
    wide_na_cftr,
    axis_title="Glia: variable L–R pairs (neuro / axon keywords; BEST4 CFTR-hi/lo)",
    suptitle="Differential CCC (ileum LIANA): Glia vs epithelial subsets, neuro/axon (BEST4 CFTR split)",
    outfile=FIG_DIR / "fig_epithelium_glia_diff_heatmap_neuro_axon_cftr_split.pdf",
    exclude_cols_for_ranking={GLIA_HEATMAP_CTRL_COL},
)

print("--- wide_cftr (gene-panel input): shape =", wide_cftr.shape)
print("  index type:", type(wide_cftr.index).__name__, "; names:", getattr(wide_cftr.index, "names", None))
if len(wide_cftr):
    _w0 = wide_cftr.index[0]
    print("  first index value repr:", repr(_w0))
    _tmp = wide_cftr.reset_index()
    print("  reset_index() first columns:", list(_tmp.columns[:4]))
    print("  first row L/R from reset_index (cols 0,1):", _tmp.iloc[0, 0], "|", _tmp.iloc[0, 1])
    _probe = (str(_tmp.iloc[0, 0]) + " " + str(_tmp.iloc[0, 1])).upper()
    for _g in ("CFTR", "SYN1", "GUCA2A", "PCLO"):
        print(f"  substring '{_g}' in first-row L+R string:", _g in _probe)
    _hit = sum(
        1
        for i in range(min(5000, len(_tmp)))
        if any(x in (str(_tmp.iloc[i, 0]) + str(_tmp.iloc[i, 1])).upper() for x in ("CFTR", "SYN1", "GUCA2A"))
    )
    print("  rows (first 5000) with CFTR or SYN1 or GUCA2A substring in L+R:", _hit)

if wide_cftr[FOCUS_CFTR_COL].notna().any():
    plot_glia_epithelium_diff_heatmap(
        wide_cftr,
        axis_title="Glia: epithelial contexts (BEST4 split by CFTR); rows = top lrscore in CFTR-hi BEST4",
        suptitle="Differential CCC (ileum): Glia vs epithelium (BEST4 CFTR-high focus)",
        outfile=FIG_DIR / "fig_epithelium_glia_diff_heatmap_best4_cftr_split.pdf",
        exclude_cols_for_ranking={GLIA_HEATMAP_CTRL_COL},
        rank_by_column=FOCUS_CFTR_COL,
    )
else:
    print("Skip BEST4 CFTR-split heatmap: no non-null scores in", FOCUS_CFTR_COL)

# --- Epithelium–Glia heatmap: curated BEST4 / ion / neuropod & synaptic gene panel (human HGNC symbols) ---
NEUROPOD_EPITHELIAL_GENE_TOKENS = {
    "BEST4",
    "CFTR",
    "OTOP2",
    "CA7",
    "GUCA2A",
    "GUCA2B",
    "GUCY2C",
    "SYT3",
    "SYN1",
    "PCLO",
    "BSN",
    "UNC13B",
    "RIMS2",
    "NOTCH2",
    "HOMER3",
    "DLG4",
    "SLC17A7",
    "SLC17A6",
    "NRXN1",
    "NRXN2",
    "NRXN3",
    "NLGN1",
    "NLGN2",
    "NLGN3",
    "NLGN4",
    "EFNB1",
    "EFNB2",
    "EFNB3",
    "EPHA2",
    "EPHA4",
    "EPHA7",
    "EPHB2",
    "EPHB4",
    "EPHB6",
    "LRRTM1",
    "LRRTM2",
    "LRRTM3",
    "LRRTM4",
    "LRRC4",
    "LRRC4B",
    "LRRC4C",
    "NCAM1",
    "L1CAM",
    "CADM1",
    "CADM2",
    "CADM3",
    "PTPRF",
    "DSCAM",
    "OPCML",
    "NTRK1",
    "GFRA1",
    "GFRA2",
    "GFRA3",
    "GFRA4",
    "RET",
    "NGF",
    "ARTN",
    "GDNF",
    "NRTN",
    "SEMA3A",
    "SEMA3C",
    "SEMA3F",
    "SEMA4A",
    "PLXNA1",
    "PLXNA2",
    "PLXNA3",
    "PLXNA4",
    "PLXNB1",
    "PLXNB2",
    "PLXNC1",
    "NRP1",
    "NRP2",
    "NTN1",
    "NTN4",
    "DCC",
    "UNC5A",
    "UNC5B",
    "UNC5C",
    "UNC5D",
    "SLIT1",
    "SLIT2",
    "SLIT3",
    "ROBO1",
    "ROBO2",
    "ROBO3",
    "ROBO4",
}
NEUROPOD_EPITHELIAL_GENE_TOKENS = {g.upper() for g in NEUROPOD_EPITHELIAL_GENE_TOKENS}


def _lr_tokens_gene_panel(lig: str, rec: str) -> set[str]:
    s = re.sub(r"[\^]+", " ", f"{lig} {rec}")
    return set(re.findall(r"[A-Za-z0-9]+", s.upper()))


def _gene_hits_lr_string(lig: str, rec: str, tokens: set[str]) -> bool:
    """True if any panel gene appears as a token or as a bounded alphanumeric span in L+R."""
    tks = _lr_tokens_gene_panel(lig, rec)
    if tks & tokens:
        return True
    blob = f" {lig} {rec} "
    blob_u = blob.upper()
    for g in tokens:
        if len(g) < 2:
            continue
        if re.search(r"(?<![A-Z0-9])" + re.escape(g) + r"(?![A-Z0-9])", blob_u):
            return True
    return False


def wide_rows_hitting_gene_panel(wide_df: pd.DataFrame, tokens: set[str]) -> pd.DataFrame:
    """Keep rows whose ligand/receptor strings hit the panel (uses reset_index — robust to index quirks)."""
    if wide_df.empty:
        return wide_df.head(0)
    t = wide_df.reset_index()
    if t.shape[1] < 2:
        return wide_df.head(0)
    lg, rc = t.iloc[:, 0], t.iloc[:, 1]
    mask = []
    for L, R in zip(lg, rc):
        if pd.isna(L) and pd.isna(R):
            mask.append(False)
            continue
        mask.append(_gene_hits_lr_string(str(L), str(R), tokens))
    m = np.array(mask, dtype=bool)
    if not m.any():
        return wide_df.head(0)
    return wide_df.iloc[m]


def _count_liana_glia_epi_panel_hits(df: pd.DataFrame, epithelial: str, tokens: set[str]) -> int:
    sub = _fill_ligand_receptor_complex_from_simple(_glia_epi_block(df, epithelial))
    if sub.empty or not {"ligand_complex", "receptor_complex"}.issubset(sub.columns):
        return 0
    n = 0
    for _, row in sub.iterrows():
        if _gene_hits_lr_string(str(row["ligand_complex"]), str(row["receptor_complex"]), tokens):
            n += 1
    return n


print(
    "  De novo LIANA panel hits (Glia↔epi rows): df_hi =",
    _count_liana_glia_epi_panel_hits(df_hi, "BEST4_Ent_CFTRhi", NEUROPOD_EPITHELIAL_GENE_TOKENS),
    "df_lo =",
    _count_liana_glia_epi_panel_hits(df_lo, "BEST4_Ent_CFTRlo", NEUROPOD_EPITHELIAL_GENE_TOKENS),
)

wide_np = wide_rows_hitting_gene_panel(wide_cftr, NEUROPOD_EPITHELIAL_GENE_TOKENS)
print(
    "Neuropod/BEST4 ion/synaptic panel: L–R pairs matching curated genes:",
    wide_np.shape[0],
)
if wide_np.empty:
    print("Skip gene-panel heatmap: no L–R pairs matched the curated gene list.")
else:
    rk = FOCUS_CFTR_COL if wide_np[FOCUS_CFTR_COL].notna().any() else None
    plot_glia_epithelium_diff_heatmap(
        wide_np,
        axis_title="Glia: epithelial contexts (BEST4 CFTR-hi/lo + subsets); rows = panel genes; rank by CFTR-hi if available",
        suptitle="Epithelium–Glia CCC: BEST4 / guanylate / neuropod & synaptic gene panel",
        outfile=FIG_DIR / "fig_epithelium_glia_neuropod_epithelial_gene_panel.pdf",
        exclude_cols_for_ranking={GLIA_HEATMAP_CTRL_COL},
        rank_by_column=rk,
        top_n=min(40, max(1, wide_np.shape[0])),
    )

# --- Villus / column epithelium: Glia + BEST4 colon + lower villus + villus tip ---
ad_back2 = sc.read_h5ad(INTEGRATED, backed="r")
obs2 = ad_back2.obs
mask_ile2 = obs2[TISSUE_COL].astype(str).str.lower().str.contains("ileum", na=False)
vtypes = {"Glia", "BEST4 Colonocytes", "Lower Villus Enterocytes", "Villus Tip Enterocytes"}
mask_v = obs2["hgca_celltype_v1"].astype(str).isin(vtypes)
ix2 = np.where((mask_ile2 & mask_v).values)[0]
print("Ileum cells for villus-column LIANA:", len(ix2))
ad_v = ad_back2[ix2].to_memory()
if hasattr(ad_back2, "file") and ad_back2.file is not None:
    ad_back2.file.close()
if "gene_symbol" in ad_v.var.columns:
    ad_v.var_names = ad_v.var["gene_symbol"].astype(str).values
    ad_v.var_names_make_unique()

df_v = pd.DataFrame()
if ad_v.n_obs and ad_v.obs["hgca_celltype_v1"].value_counts().min() >= 5:
    try:
        outv = li.mt.rank_aggregate(
            ad_v,
            groupby="hgca_celltype_v1",
            resource_name="consensus",
            expr_prop=0.1,
            use_raw=False,
            inplace=False,
            verbose=False,
        )
        if isinstance(outv, tuple):
            outv = outv[0]
        df_v = outv if isinstance(outv, pd.DataFrame) else pd.DataFrame()
    except Exception as e:
        print("LIANA villus-column failed:", e)
        df_v = pd.DataFrame()
else:
    print("Skip villus-column LIANA: too few cells in a group")

s_col = _lr_series_from_liana(df_v, "BEST4 Colonocytes", "BEST4 colonocyte")
s_lv = _lr_series_from_liana(df_v, "Lower Villus Enterocytes", "Villus bottom")
s_vt = _lr_series_from_liana(df_v, "Villus Tip Enterocytes", "Villus tip")
wide_vcol = pd.concat([s_col, s_lv, s_vt], axis=1)
if not wide_vcol.empty and wide_vcol.notna().any().any():
    plot_glia_epithelium_diff_heatmap(
        wide_vcol,
        axis_title="Glia ↔ column epithelium (BEST4 colon, lower villus, villus tip)",
        suptitle="Differential CCC (ileum): Glia vs villus-column enterocytes",
        outfile=FIG_DIR / "fig_epithelium_glia_villus_column_heatmap.pdf",
        exclude_cols_for_ranking=None,
        rank_by_column=None,
    )
else:
    print("Skip villus-column heatmap: empty or all-NaN wide table")

Ileum Glia+BEST4 cells for CFTR split: 2836
ad_cf var_names use gene symbols (post-mapping): n_var = 35574 ; CFTR present: True
BEST4 ileum: CFTR-hi 1027 CFTR-lo 1023 median log1p thr 1.6094
LIANA subset hi: {'BEST4_Ent_CFTRhi': 1027, 'Glia': 786}

/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/anndata/_core/anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/_pipe_utils/_pre.py:266: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/_pipe_utils/_pre.py:149: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/functools.py:909: UserWarning: zero-centering a sparse array/matrix densifies it.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/sc/_liana_pipe.py:288: ImplicitModificationWarning: Setting element `.layers['scaled']` of view, initializing view as actual.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/sc/_liana_pipe.py:386: RuntimeWarning: overflow encountered in power

LIANA subset lo: {'BEST4_Ent_CFTRlo': 1023, 'Glia': 786}

/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/anndata/_core/anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/_pipe_utils/_pre.py:266: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/_pipe_utils/_pre.py:149: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/functools.py:909: UserWarning: zero-centering a sparse array/matrix densifies it.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/sc/_liana_pipe.py:288: ImplicitModificationWarning: Setting element `.layers['scaled']` of view, initializing view as actual.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/sc/_liana_pipe.py:386: RuntimeWarning: overflow encountered in power
maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 71 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'four', 'g', 'h', 'hyphen', 'i', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 51, 53, 54, 55, 56, 57, 58, 59, 60, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 178, 179]
Closed glyph list over 'glyf': 71 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'four', 'g', 'h', 'hyphen', 'i', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 51, 53, 54, 55, 56, 57, 58, 59, 60, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 178, 179]
Retaining 71 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned

Note: rank_aggregate includes within-group (source==target) rows in df_hi/df_lo; heatmap Glia columns use only Glia↔epithelial pairs (_glia_epi_block), not autocrine.
--- df_hi: shape=(1167, 13)
  columns: ['source', 'target', 'ligand_complex', 'receptor_complex', 'lr_means', 'cellphone_pvals', 'expr_prod', 'scaled_weight', 'lr_logfc', 'spec_weight', 'lrscore', 'specificity_rank', 'magnitude_rank']
  has {'target', 'ligand_complex', 'source', 'receptor_complex'} ? {'target': True, 'ligand_complex': True, 'source': True, 'receptor_complex': True}
  sample Glia↔epi row (ligand_complex, receptor_complex): {'ligand_complex': 'S100A10', 'receptor_complex': 'CFTR'}
--- df_lo: shape=(1104, 13)
  columns: ['source', 'target', 'ligand_complex', 'receptor_complex', 'lr_means', 'cellphone_pvals', 'expr_prod', 'scaled_weight', 'lr_logfc', 'spec_weight', 'lrscore', 'specificity_rank', 'magnitude_rank']
  has {'target', 'ligand_complex', 'source', 'receptor_complex'} ? {'target': True, 'ligand_complex': True, 'source': True, 'receptor_complex': True}
  sample Glia↔epi row (ligand_complex, receptor_complex): {'ligand_complex': 'LGALS3', 'receptor_complex': 'MCAM'}
Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_diff_heatmap_all_cftr_split.pdf

maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 70 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 57, 58, 59, 60, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 178, 179]
Closed glyph list over 'glyf': 70 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 47, 48, 49, 50, 51, 53, 54, 55, 57, 58, 59, 60, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 178, 179]
Retaining 70 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_diff_heatmap_neuro_axon_cftr_split.pdf
--- wide_cftr (gene-panel input): shape = (4460, 10)
  index type: MultiIndex ; names: ['ligand_complex', 'receptor_complex']
  first index value repr: ('A2M', 'LRP1')
  reset_index() first columns: ['ligand_complex', 'receptor_complex', 'EEC L', 'EEC (mature)']
  first row L/R from reset_index (cols 0,1): A2M | LRP1
  substring 'CFTR' in first-row L+R string: False
  substring 'SYN1' in first-row L+R string: False
  substring 'GUCA2A' in first-row L+R string: False
  substring 'PCLO' in first-row L+R string: False
  rows (first 5000) with CFTR or SYN1 or GUCA2A substring in L+R: 3

maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 68 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'V', 'X', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 53, 54, 55, 57, 59, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 179]
Closed glyph list over 'glyf': 68 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'V', 'X', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 53, 54, 55, 57, 59, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 179]
Retaining 68 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_diff_heatmap_best4_cftr_split.pdf
  De novo LIANA panel hits (Glia↔epi rows): df_hi = 50 df_lo = 41

maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 73 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'X', 'a', 'ampersand', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 9, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, 57, 59, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 178, 179]
Closed glyph list over 'glyf': 73 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'V', 'X', 'a', 'ampersand', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 9, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, 57, 59, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 178, 179]
Retaining 73 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned

Neuropod/BEST4 ion/synaptic panel: L–R pairs matching curated genes: 309
Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_neuropod_epithelial_gene_panel.pdf
Ileum cells for villus-column LIANA: 74049

/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/anndata/_core/anndata.py:381: FutureWarning: The dtype argument is deprecated and will be removed in late 2024.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/_pipe_utils/_pre.py:146: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/_pipe_utils/_pre.py:149: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/functools.py:909: UserWarning: zero-centering a sparse array/matrix densifies it.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/sc/_liana_pipe.py:288: ImplicitModificationWarning: Setting element `.layers['scaled']` of view, initializing view as actual.
/Users/kylekimler/miniforge3/envs/scanpy/lib/python3.11/site-packages/liana/method/sc/_liana_pipe.py:386: RuntimeWarning: overflow encountered in power
/var/folders/zc/5fly3ly908xb0pd8zy6m6bj80000gn/T/ipykernel_96935/3147547659.py:59: UserWarning: Glyph 8596 (\N{LEFT RIGHT ARROW}) missing from font(s) Helvetica.
maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Missing glyphs for requested Unicodes: ['U+2194']
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 68 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'V', 'X', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 59, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 179]
Closed glyph list over 'glyf': 68 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'V', 'X', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'l', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'w', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 57, 59, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 90, 91, 92, 179]
Retaining 68 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig_epithelium_glia_villus_column_heatmap.pdf

In [11]:
df_hi

,source,target,ligand_complex,receptor_complex,lr_means,cellphone_pvals,expr_prod,scaled_weight,lr_logfc,spec_weight,lrscore,specificity_rank,magnitude_rank
150,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,GUCA2A,GUCY2C,98.801437,0.000,582.499817,0.465978,inf,0.998622,0.985714,0.000155,0.000007
151,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,GUCA2B,GUCY2C,91.128555,0.000,536.567322,0.422275,inf,0.998719,0.985124,0.000355,0.000026
265,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,S100A10,CFTR,17.455683,0.000,271.931152,0.435845,155.135856,0.761938,0.979228,0.035359,0.000059
157,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,HLA-A,APLP2,10.070084,0.000,52.393082,0.341398,137.931851,0.606513,0.953902,0.093942,0.000237
824,Glia,BEST4_Ent_CFTRhi,S100A10,CFTR,9.485193,1.000,84.924347,0.008319,83.000321,0.237954,0.963430,0.642707,0.000421
...,...,...,...,...,...,...,...,...,...,...,...,...,...
293,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,TGFB1,ITGB8,0.335443,0.759,0.083982,0.004592,-3.354572,0.266905,0.453095,1.000000,1.000000
292,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,TGFB1,ITGB5,0.302337,0.000,0.072957,0.171729,1.066342,0.560817,0.435724,0.605762,1.000000
259,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,PSEN1,NOTCH1,0.567671,0.000,0.150193,0.160562,4.054990,0.423553,0.525599,0.445058,1.000000
24,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,ANG,EGFR,0.311587,0.000,0.089910,0.171198,2.993143,0.630864,0.461560,0.245743,1.000000
311,BEST4_Ent_CFTRhi,BEST4_Ent_CFTRhi,WNT2B,FZD5_LRP5,0.277507,0.000,0.067529,0.181048,2.451067,0.730678,0.426244,0.208332,1.000000

## 4. Differential CCC (FARM ↔ CD4 subsets)
Compare **max lrscore per ligand–receptor** between CD4 populations (same ileum LIANA table). **Two heatmaps**: (1) all variable pairs; (2) **only** pairs where ligand/receptor tokens hit **OpenTargets GWAS** (`FARM_GWAS_GENES`) or **monocyte drug-target** (`FARM_DRUG_MONOCYTE_GENES`) lists — saved as `fig4_diff_ccc_farm_cd4_heatmap_opentargets.pdf`. **Tr1 vs Tfr** scatter and Δ plots use the same gene token logic — **not** neuro/axon colours (those are in §epithelium–Glia). NKT / γδ T omitted from CD4 heatmaps.

In [12]:
T_CD4 = [
    "CD4 Tr1",
    "CD4 Tfr",
    "CD4 Tfh",
    "CD4 pTreg",
    "CD4 Th17",
    "CD4 tTreg",
]

# OpenTargets / genetic vulnerability in FARMs (curated from your analysis)
FARM_GWAS_GENES = {
    "PTPN22",
    "FOSL2",
    "GPR35",
    "NDFIP1",
    "NR3C1",
    "TAGAP",
    "JAZF1",
    "IKZF1",
    "IRF5",
    "MAP3K8",
    "TSPAN14",
    "ITGB7",
    "LACC1",
    "PTPN2",
    "NCF4",
    "IFNGR2",
}
# Biologic & classical monocyte/macrophage drug targets (anti-TNF → TNFAIP3/TNF axis; vedolizumab integrins; ustekinumab IL-12/23; JAKi) — often lower on FARMs vs other monocyte subsets in druggability views
FARM_DRUG_MONOCYTE_GENES = {
    "TNFAIP3",
    "TNF",
    "TNFRSF1A",
    "TNFRSF1B",
    "IL12B",
    "IL23A",
    "IL23R",
    "IL12RB1",
    "IL12RB2",
    "JAK1",
    "JAK2",
    "TYK2",
    "ITGA4",
    "ITGB7",
    "NFKB1",
    "RELA",
}
GWAS_TOK = {g.upper() for g in FARM_GWAS_GENES}
DRUG_TOK = {g.upper() for g in FARM_DRUG_MONOCYTE_GENES}


def _lr_tokens(lig: str, rec: str) -> set[str]:
    return set(re.findall(r"[A-Za-z0-9]+", f"{lig}{rec}".upper()))


def farm_lr_is_opentarget_pair(lig: str, rec: str) -> bool:
    """True if ligand or receptor token matches GWAS or monocyte drug-target lists."""
    tok = _lr_tokens(lig, rec)
    return bool((tok & GWAS_TOK) | (tok & DRUG_TOK))


def farm_opentargets_category(row: pd.Series) -> str:
    lig = str(row.get("ligand", row.get("ligand_complex", "")))
    rec = str(row.get("receptor", row.get("receptor_complex", "")))
    tok = _lr_tokens(lig, rec)
    g = bool(tok & GWAS_TOK)
    d = bool(tok & DRUG_TOK)
    if g and d:
        return "both"
    if g:
        return "gwas"
    if d:
        return "drug"
    return "other"


series_list = []
for t in T_CD4:
    if t not in farm_tables or farm_tables[t].empty:
        continue
    m = max_lr_per_pair(farm_tables[t])
    s = m.set_index(["ligand_complex", "receptor_complex"])["lrscore"].rename(t)
    series_list.append(s)

if not series_list:
    raise RuntimeError("No CD4 FARM tables — re-run load with CD4 tTreg in watchlist.")

wide = pd.concat(series_list, axis=1)
# Pairs most variable across CD4 subsets (rank by std)
rank_var = wide.std(axis=1, skipna=True).dropna().sort_values(ascending=False)
if rank_var.empty:
    rank_var = wide.max(axis=1, skipna=True).sort_values(ascending=False)
top_n = min(40, len(rank_var))
pair_idx = rank_var.head(top_n).index
heat = wide.loc[pair_idx]

fig_h, ax_h = plt.subplots(figsize=(7.2, 8.8))
fig_h.subplots_adjust(bottom=0.2, top=0.86)
panel_label(ax_h, "a)")
data = np.ma.masked_invalid(heat.values.astype(float))
vmin_h = float(np.nanmin(heat.values))
vmax_h = float(np.nanmax(heat.values))
if vmin_h == vmax_h:
    vmax_h = vmin_h + 1e-9
im = ax_h.imshow(data, aspect="auto", cmap=NATURE_CMAP, vmin=vmin_h, vmax=vmax_h)
ax_h.set_yticks(np.arange(len(heat)))
ylabs = [shorten_label(f"{a} — {b}") for a, b in heat.index]
ax_h.set_yticklabels(ylabs, fontsize=5, color=NATURE_WONG["black"])
ax_h.set_xticks(np.arange(heat.shape[1]))
ax_h.set_xticklabels([c.replace("CD4 ", "") for c in heat.columns], rotation=45, ha="right", fontsize=6, color=NATURE_WONG["black"])
ax_h.set_title("FARM <-> CD4: variable ligand–receptor pairs (max lrscore)", fontsize=7, color=NATURE_WONG["black"])
cbar = fig_h.colorbar(im, ax=ax_h, fraction=0.035, pad=0.02)
cbar.ax.tick_params(colors=NATURE_WONG["black"])
cbar.set_label("lrscore (unitless)", color=NATURE_WONG["black"], fontsize=6)
for t in cbar.ax.get_yticklabels():
    t.set_color(NATURE_WONG["black"])
fig_h.suptitle("Differential CCC (ileum LIANA): FARM vs CD4 subsets", fontsize=7, color=NATURE_WONG["black"], y=0.98)
fig_h.text(
    0.5,
    0.06,
    LIANA_NOTE_FARM_HEATMAP,
    ha="center",
    va="top",
    fontsize=5.5,
    color=NATURE_WONG["black"],
    transform=fig_h.transFigure,
)
save_pdf(fig_h, FIG_DIR / "fig4_diff_ccc_farm_cd4_heatmap.pdf")

# --- FARM CD4 heatmap: OpenTargets GWAS + drug-target genes only ---
wide_ot = wide.loc[
    [farm_lr_is_opentarget_pair(str(a), str(b)) for a, b in wide.index],
    :,
]
if wide_ot.empty:
    print("No FARM CD4 pairs matched OpenTargets GWAS/drug lists (opentargets heatmap skipped).")
else:
    rank_var_ot = wide_ot.std(axis=1, skipna=True).dropna().sort_values(ascending=False)
    if rank_var_ot.empty:
        rank_var_ot = wide_ot.max(axis=1, skipna=True).sort_values(ascending=False)
    top_n_ot = min(40, len(rank_var_ot))
    heat_ot = wide_ot.loc[rank_var_ot.head(top_n_ot).index]
    fig_hot, ax_hot = plt.subplots(figsize=(7.2, 8.8))
    fig_hot.subplots_adjust(bottom=0.2, top=0.86)
    panel_label(ax_hot, "a)")
    data_ot = np.ma.masked_invalid(heat_ot.values.astype(float))
    vmin_ot = float(np.nanmin(heat_ot.values))
    vmax_ot = float(np.nanmax(heat_ot.values))
    if vmin_ot == vmax_ot:
        vmax_ot = vmin_ot + 1e-9
    im_ot = ax_hot.imshow(data_ot, aspect="auto", cmap=NATURE_CMAP, vmin=vmin_ot, vmax=vmax_ot)
    ax_hot.set_yticks(np.arange(len(heat_ot)))
    ax_hot.set_yticklabels(
        [shorten_label(f"{a} — {b}") for a, b in heat_ot.index],
        fontsize=5,
        color=NATURE_WONG["black"],
    )
    ax_hot.set_xticks(np.arange(heat_ot.shape[1]))
    ax_hot.set_xticklabels(
        [c.replace("CD4 ", "") for c in heat_ot.columns],
        rotation=45,
        ha="right",
        fontsize=6,
        color=NATURE_WONG["black"],
    )
    ax_hot.set_title(
        "FARM <-> CD4: variable pairs (GWAS / drug-target genes only)",
        fontsize=7,
        color=NATURE_WONG["black"],
    )
    cbar_ot = fig_hot.colorbar(im_ot, ax=ax_hot, fraction=0.035, pad=0.02)
    cbar_ot.ax.tick_params(colors=NATURE_WONG["black"])
    cbar_ot.set_label("lrscore (unitless)", color=NATURE_WONG["black"], fontsize=6)
    for t in cbar_ot.ax.get_yticklabels():
        t.set_color(NATURE_WONG["black"])
    fig_hot.suptitle(
        "Differential CCC (ileum LIANA): FARM vs CD4 (OpenTargets GWAS & drug targets)",
        fontsize=7,
        color=NATURE_WONG["black"],
        y=0.98,
    )
    fig_hot.text(
        0.5,
        0.06,
        LIANA_NOTE_FARM_HEATMAP,
        ha="center",
        va="top",
        fontsize=5.5,
        color=NATURE_WONG["black"],
        transform=fig_hot.transFigure,
    )
    save_pdf(fig_hot, FIG_DIR / "fig4_diff_ccc_farm_cd4_heatmap_opentargets.pdf")

# --- Tr1 vs Tfr: scatter of matched pairs ---
tr1 = max_lr_per_pair(farm_tables["CD4 Tr1"]).rename(columns={"lrscore": "CD4 Tr1"})
tfr = max_lr_per_pair(farm_tables["CD4 Tfr"]).rename(columns={"lrscore": "CD4 Tfr"})
m12 = tr1.merge(tfr, on=["ligand_complex", "receptor_complex"], how="inner")
m12 = m12.rename(columns={"ligand_complex": "ligand", "receptor_complex": "receptor"})
m12["farm_cat"] = m12.apply(farm_opentargets_category, axis=1)

fig_s, ax_s = plt.subplots(figsize=(3.5, 3.5))
panel_label(ax_s, "b)")
farm_style = {
    "other": (NATURE_WONG["yellow"], 8, 0.45, "Other L–R pairs"),
    "gwas": (NATURE_WONG["sky_blue"], 11, 0.8, "GWAS vulnerability (FARM)"),
    "drug": (NATURE_WONG["bluish_green"], 11, 0.8, "Biologic / monocyte drug targets"),
    "both": (NATURE_WONG["vermillion"], 14, 0.92, "GWAS + drug-target genes"),
}
for cat in ['other', 'gwas', 'drug', 'both']:
    m = m12['farm_cat'] == cat
    if not m.any():
        continue
    ccol, siz, alp, lab = farm_style[cat]
    ax_s.scatter(
        m12.loc[m, 'CD4 Tr1'],
        m12.loc[m, 'CD4 Tfr'],
        s=siz,
        c=ccol,
        edgecolors=NATURE_WONG['black'],
        linewidths=0.35,
        alpha=alp,
        label=lab,
    )
lim = float(max(m12["CD4 Tr1"].max(), m12["CD4 Tfr"].max()))
ax_s.plot([0, lim], [0, lim], color=NATURE_WONG["black"], linewidth=0.6, linestyle="--", alpha=0.7)
ax_s.set_xlabel("lrscore FARM <-> CD4 Tr1 (unitless)", color=NATURE_WONG["black"])
ax_s.set_ylabel("lrscore FARM <-> CD4 Tfr (unitless)", color=NATURE_WONG["black"])
ax_s.set_title("Matched pairs: Tr1 vs Tfr", fontsize=7, color=NATURE_WONG["black"])
leg = ax_s.legend(frameon=False, loc="upper left", handlelength=1.2, fontsize=5.5)
for text in leg.get_texts():
    text.set_color(NATURE_WONG["black"])
ax_s.tick_params(colors=NATURE_WONG["black"])
fig_s.subplots_adjust(bottom=0.2)
fig_s.suptitle("Differential CCC: Tr1 vs Tfr (OpenTargets GWAS & drug targets)", fontsize=7, color=NATURE_WONG["black"], y=1.08)
fig_s.text(
    0.5,
    0.03,
    LIANA_NOTE_SHORT,
    ha="center",
    va="bottom",
    fontsize=5,
    color=NATURE_WONG["black"],
    transform=fig_s.transFigure,
)
save_pdf(fig_s, FIG_DIR / "fig5_tr1_vs_tfr_scatter.pdf")

# --- Bar: largest Tr1 − Tfr differences ---
m12["delta_tr1_minus_tfr"] = m12["CD4 Tr1"] - m12["CD4 Tfr"]
topd = m12.reindex(m12["delta_tr1_minus_tfr"].abs().sort_values(ascending=False).index).head(18)
fig_d, ax_d = plt.subplots(figsize=(3.5, 5.5))
panel_label(ax_d, "c)")
y = np.arange(len(topd))
col_farm = {
    "other": NATURE_WONG["yellow"],
    "gwas": NATURE_WONG["sky_blue"],
    "drug": NATURE_WONG["bluish_green"],
    "both": NATURE_WONG["vermillion"],
}
cols_bar = [col_farm[farm_opentargets_category(row)] for _, row in topd.iterrows()]
ax_d.barh(y, topd["delta_tr1_minus_tfr"], color=cols_bar, edgecolor=NATURE_WONG["black"], linewidth=0.35)
labs = [shorten_label(f"{a} — {b}") for a, b in zip(topd["ligand"], topd["receptor"])]
ax_d.set_yticks(y)
ax_d.set_yticklabels(labs, fontsize=5.5, color=NATURE_WONG["black"])
ax_d.invert_yaxis()
ax_d.set_xlabel("Δ lrscore (Tr1 − Tfr) (unitless)", color=NATURE_WONG["black"])
ax_d.set_title("Largest |Tr1−Tfr| shifts (FARM-linked)", fontsize=7, color=NATURE_WONG["black"])
ax_d.axvline(0, color=NATURE_WONG["black"], linewidth=0.5)
ax_d.tick_params(colors=NATURE_WONG["black"])
ax_d.spines["top"].set_visible(False)
ax_d.spines["right"].set_visible(False)
leg_p = [
    Patch(facecolor=NATURE_WONG["vermillion"], edgecolor=NATURE_WONG["black"], label="GWAS + drug-target"),
    Patch(facecolor=NATURE_WONG["sky_blue"], edgecolor=NATURE_WONG["black"], label="GWAS (FARM)"),
    Patch(facecolor=NATURE_WONG["bluish_green"], edgecolor=NATURE_WONG["black"], label="Drug targets"),
    Patch(facecolor=NATURE_WONG["yellow"], edgecolor=NATURE_WONG["black"], label="Other"),
]
leg2 = ax_d.legend(handles=leg_p, frameon=False, loc="lower right", fontsize=5.5)
for t in leg2.get_texts():
    t.set_color(NATURE_WONG["black"])
fig_d.subplots_adjust(bottom=0.18)
fig_d.suptitle("Differential CCC: Tr1 vs Tfr (OpenTargets)", fontsize=7, color=NATURE_WONG["black"], y=1.02)
fig_d.text(
    0.5,
    0.02,
    LIANA_NOTE_SHORT,
    ha="center",
    va="bottom",
    fontsize=5,
    color=NATURE_WONG["black"],
    transform=fig_d.transFigure,
)
save_pdf(fig_d, FIG_DIR / "fig6_delta_tr1_minus_tfr.pdf")

maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 68 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'V', 'X', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'five', 'four', 'g', 'greater', 'h', 'hyphen', 'i', 'l', 'less', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'x', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 53, 54, 55, 57, 59, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 178, 179]
Closed glyph list over 'glyf': 68 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'V', 'X', 'Z', 'a', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'endash', 'equal', 'f', 'five', 'four', 'g', 'greater', 'h', 'hyphen', 'i', 'l', 'less', 'm', 'n', 'nine', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'x', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 15, 16, 17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 53, 54, 55, 57, 59, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 178, 179]
Retaining 68 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned
maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 63 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'F', 'G', 'I', 'L', 'M', 'N', 'O', 'R', 'S', 'T', 'V', 'W', 'a', 'ampersand', 'b', 'c', 'colon', 'comma', 'd', 'e', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'greater', 'h', 'hyphen', 'i', 'l', 'less', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 9, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 29, 30, 31, 32, 33, 36, 37, 38, 39, 41, 42, 44, 47, 48, 49, 50, 53, 54, 55, 57, 58, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 179]
Closed glyph list over 'glyf': 63 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'F', 'G', 'I', 'L', 'M', 'N', 'O', 'R', 'S', 'T', 'V', 'W', 'a', 'ampersand', 'b', 'c', 'colon', 'comma', 'd', 'e', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'greater', 'h', 'hyphen', 'i', 'l', 'less', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'r', 's', 'semicolon', 'seven', 'six', 'slash', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'x', 'y', 'zero']
Glyph IDs:   [0, 1, 2, 3, 9, 11, 12, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 29, 30, 31, 32, 33, 36, 37, 38, 39, 41, 42, 44, 47, 48, 49, 50, 53, 54, 55, 57, 58, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 92, 179]
Retaining 63 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig4_diff_ccc_farm_cd4_heatmap.pdf
Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig4_diff_ccc_farm_cd4_heatmap_opentargets.pdf

maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 56 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'F', 'G', 'L', 'M', 'O', 'R', 'S', 'T', 'W', 'a', 'ampersand', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'endash', 'equal', 'f', 'four', 'g', 'greater', 'h', 'hyphen', 'i', 'l', 'less', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'six', 'space', 't', 'two', 'u', 'v', 'x', 'zero']
Glyph IDs:   [0, 1, 2, 3, 9, 11, 12, 14, 15, 16, 17, 19, 20, 21, 23, 25, 27, 29, 30, 31, 32, 33, 36, 37, 38, 39, 41, 42, 47, 48, 50, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 178]
Closed glyph list over 'glyf': 56 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'F', 'G', 'L', 'M', 'O', 'R', 'S', 'T', 'W', 'a', 'ampersand', 'b', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'endash', 'equal', 'f', 'four', 'g', 'greater', 'h', 'hyphen', 'i', 'l', 'less', 'm', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'six', 'space', 't', 'two', 'u', 'v', 'x', 'zero']
Glyph IDs:   [0, 1, 2, 3, 9, 11, 12, 14, 15, 16, 17, 19, 20, 21, 23, 25, 27, 29, 30, 31, 32, 33, 36, 37, 38, 39, 41, 42, 47, 48, 50, 53, 54, 55, 58, 68, 69, 70, 71, 72, 73, 74, 75, 76, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 178]
Retaining 56 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 31]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned
maxp pruned
cmap pruned
1 extra bytes in post.stringData array
kern pruned
post pruned
Zapf dropped
feat dropped
meta dropped
morx dropped
'created' timestamp seems very low; regarding as unix timestamp
glyf pruned
Added gid0 to subset
Added first four glyphs to subset
Closing glyph list over 'glyf': 66 glyphs before
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'Deltagreek', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'Z', 'a', 'b', 'bar', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'minus', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'x', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 27, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 53, 54, 55, 58, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 95, 179, 239, 1091]
Closed glyph list over 'glyf': 66 glyphs after
Glyph names: ['.notdef', '.null', 'A', 'B', 'C', 'D', 'Deltagreek', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'W', 'Z', 'a', 'b', 'bar', 'c', 'colon', 'comma', 'd', 'e', 'eight', 'emdash', 'equal', 'f', 'five', 'four', 'g', 'h', 'hyphen', 'i', 'k', 'l', 'm', 'minus', 'n', 'nonmarkingreturn', 'o', 'one', 'p', 'parenleft', 'parenright', 'period', 'plus', 'r', 's', 'semicolon', 'space', 't', 'three', 'two', 'u', 'underscore', 'v', 'x', 'zero']
Glyph IDs:   [0, 1, 2, 3, 11, 12, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 27, 29, 30, 32, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 53, 54, 55, 58, 61, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 78, 79, 80, 81, 82, 83, 85, 86, 87, 88, 89, 91, 95, 179, 239, 1091]
Retaining 66 glyphs
head subsetting not needed
hhea subsetting not needed
maxp subsetting not needed
OS/2 subsetting not needed
hmtx subsetted
hdmx subsetted
cmap subsetted
fpgm subsetting not needed
prep subsetting not needed
cvt  subsetting not needed
loca subsetting not needed
kern subsetted
post subsetted
prop subsetted
name subsetting not needed
glyf subsetted
head pruned
OS/2 Unicode ranges pruned: [0, 7, 31, 38]
OS/2 CodePage ranges pruned: [0]
glyf pruned
name pruned

Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig5_tr1_vs_tfr_scatter.pdf
Saved /Users/kylekimler/Projects/GCA/github_vignette_output/LIANA/ileum_figures/fig6_delta_tr1_minus_tfr.pdf

## Follow-up
- **FARM scatter / Δ**: refine `FARM_GWAS_GENES` and `FARM_DRUG_MONOCYTE_GENES` against your OpenTargets exports; token matching is exact symbol overlap in LIANA `ligand_complex` / `receptor_complex` strings.
- **Glia scatter / Δ**: default contrast is **EEC (mature)** vs **Tuft** (falls back to the first two columns if missing); change `SC_A` / `SC_B` in the notebook. **Heatmaps** exclude **Villus bottom** from **row ranking** only (column still shown); edit `GLIA_HEATMAP_CTRL_COL` / `reduce_canonical_neuropeptide_outgoing` if needed.
- **BEST4 CFTR split** (all / neuro-axon differential heatmaps, focused CFTR heatmap, gene-panel, villus-column): `fig_epithelium_glia_diff_heatmap_all_cftr_split.pdf`, `fig_epithelium_glia_diff_heatmap_neuro_axon_cftr_split.pdf`, `fig_epithelium_glia_diff_heatmap_best4_cftr_split.pdf`, `fig_epithelium_glia_neuropod_epithelial_gene_panel.pdf`, `fig_epithelium_glia_villus_column_heatmap.pdf` — require **`liana`**; run the **“Epithelium–Glia: BEST4 CFTR split & villus columns”** cell **after** `wide_all` / `wide_na` are built; uses median **log1p CFTR** on ileal BEST4 enterocytes.
- Refine neuro / axon keyword lists (epithelium–Glia) against curated databases if needed.
- Optional: stricter CSV pre-filter to shrink `dfw` if memory is tight.
- **Vector workflow**: edit PDFs in Illustrator if needed, then save **.ai** for production; otherwise submit **.pdf** from above.
- **Neuropod / NCAM / GDNF–RET (§2.2):** `neuropod_glia_eec_focus_summary.csv`, `fig_neuropod_glia_*.pdf` (includes `*_GDNF_RET_GFRA*.pdf`), `neurofil_ncam_mean_log1p_by_celltype_region.csv`, `fig_neuropod_neurofil_ncam_expr_ileum_bars.pdf`.